In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from operator import add

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
pip install gensim==4.3.1

Requirement already satisfied: gensim==4.3.1 in /usr/local/lib/python3.11/dist-packages (4.3.1)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.1) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.1) (1.10.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.1) (7.1.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim==4.3.1) (1.17.2)

In [ ]:
pip install scipy==1.10.1

Requirement already satisfied: scipy==1.10.1 in /usr/local/lib/python3.11/dist-packages (1.10.1)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scipy==1.10.1) (1.26.4)

In [ ]:
from gensim.models import KeyedVectors

In [ ]:
model = KeyedVectors.load_word2vec_format("/content/drive/MyDrive/MED-enem/cbow_s300.txt")

###Vetorização dos enunciados

In [ ]:
cleaned_data = pd.read_csv("/content/drive/MyDrive/MED-enem/cleaned_data.csv")
cleaned_data.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,ano,enunciado_limpo,alternativas_limpo
0,91,Para realizar o desentupimento de tubulações d...,A: Al; B: Co; C: Cu(OH)2; D: Fe(OH)2; E: Pb,1.13773,A,2019,adicionada aumentando aumentar básico calor co...,A: al; B: co; C: cu oh; D: fe oh; E: pb
1,92,As redes de alta tensão para transmissão de en...,A: Fazer o aterramento dos arames da cerca.; B...,1.45214,A,2019,alta animais aproximarem arame campo cerca cer...,A: arames aterramento cerca fazer; B: acrescen...
2,93,A esquistossomose (barriga-dʼágua) caracteriza...,A: impedir a penetração do parasita pela pele....,0.58402,E,2019,anticorpos após barriga baseia baço biomphalar...,A: impedir parasita pele penetração; B: caramu...
3,94,"Em 1962, um jingle (vinheta musical) criado po...",A: Aquecer a casa e os corpos.; B: Evitar a en...,0.41535,C,2019,abriria animado apesar aquecer associar batia ...,A: aquecer casa corpos; B: casa corpos entrada...
4,95,Glicólise é um processo que ocorre nas células...,A: libera 112 kJ por mol de glicose.; B: liber...,2.21432,A,2019,alguns anaeróbico casos combustão completament...,A: glicose kj libera mol; B: glicose kj libera...

In [ ]:
remover_palavras=[] #vetor de palavras que não compoem o corpus do modelo
enunciado_limpo_novo = [] #lista de palavras presentes no enunciado depois de limpo
remover = [',', '.', ':', ';', '(', ')'] #lista de caracteres específicos a serem retirados
lista_enunciados = [] #lista de enunciados vetorizados

for indice in range(len(cleaned_data['enunciado_limpo'])):
  #print(indice)
  enunciado_vet =[] #lista para armazenar os vetores de todas as palavras de um enunciado
  enunciado = cleaned_data['enunciado_limpo'][indice].split()

  #remove as palavras que não estão no corpus
  for palavra in remover_palavras:
    if palavra in enunciado:
      enunciado = [x for x in enunciado if x != palavra]

  for palavra in enunciado:
    #remove os caracteres indesejados
    for i in remover:
      palavra = palavra.replace(i, "")

    if palavra.lower() in model:
      enunciado_vet.append(model[palavra.lower()])
    else:
      remover_palavras.append(palavra)

    #enunciado_vet.append(model[palavra.lower()])
  lista_enunciados.append(enunciado_vet)

In [ ]:
len(remover_palavras)

203

In [ ]:
remover_palavras

['protanopia',
 'hidrocarbônicas',
 'calibrarem',
 'etanodiol',
 'intermembranas',
 'triprótico',
 'kônig',
 'emulsificados',
 'encapsulador',
 'nióbia',
 'cherimoia',
 'àquela',
 'hyv',
 'hoterocromalina',
 'nurchéscio',
 'redicato',
 'interconverter',
 'alquílicas',
 'ateo',
 'locoa',
 'estimulássemos',
 'excitaríamos',
 'enoico',
 'hidroxidec',
 'holometabolia',
 'planetasustentavel',
 'sedimentáveis',
 'cienciahoje',
 'indefi',
 'premenstrual',
 'reuptake',
 'hexan',
 'spneonatologia',
 'covid',
 'metilex',
 'metilpentan',
 'trimetilpentano',
 'biocarvão',
 'biochar',
 'chemmatters',
 'michalovic',
 'gazetadopovo',
 'cavagis',
 'tumorigênese',
 'dnapl',
 'canalbioenergia',
 'efundir',
 'aclimatou',
 'àquelas',
 'amínio',
 'penicilamina',
 'ogeda',
 'abocanhados',
 'nanocerâmicos',
 'demasculinized',
 'ecologically',
 'herbicide',
 'hermaphroditic',
 'collineína',
 'sanitizante',
 'sadava',
 'termogenina',
 'amonificação',
 'desnitri',
 'scienceprojectideasforkids',
 'fryhle',
 'gaultéria',
 'extinguiriam',
 'hidrolisando',
 'heteronuclear',
 'subetapa',
 'solubilizado',
 'desintoxicadas',
 'mmodelo',
 'mtorre',
 'pmodelo',
 'ptorre',
 'gastrorresistentes',
 'unifebe',
 'cianovirina',
 'viricida',
 'microbomba',
 'programaaguaazul',
 'microespectro',
 'prosab',
 'chaua',
 'cienciamao',
 'compoundchem',
 'megaespetáculos',
 'eugenioides',
 'tetraploide',
 'paleoclimatológicas',
 'eletrorrepulsão',
 'eletrosmose',
 'permeiem',
 'polionotus',
 'homogeneizá',
 'umedecê',
 'mimicry',
 'researchgate',
 'tregenza',
 'mebdownloads',
 'botal',
 'hülsendeger',
 'hyperbilirubinemia',
 'lumirrubina',
 'phototherapy',
 'astronoo',
 'catabolizados',
 'damé',
 'enegep',
 'vidauniversoydemas',
 'zalbowitz',
 'novaescola',
 'cholesteryl',
 'lysosomal',
 'semiequações',
 'alcoolômetro',
 'eletroluminescentes',
 'ngaura',
 'inovacaotecnologica',
 'canade',
 'hidrometalúrgico',
 'pirometalúrgicos',
 'eletrolisado',
 'monofluoracético',
 'estanhochumbo',
 'microvespa',
 'meselson',
 'imageiam',
 'glicocólico',
 'taurocólico',
 'remineralizando',
 'apocinaceae',
 'ithomiinae',
 'photuris',
 'polipirrol',
 'aridofolia',
 'aminometilfosfônico',
 'glicinas',
 'metilglicina',
 'sarcosina',
 'interruptora',
 'nanokid',
 'nanoputians',
 'coronopilina',
 'respectivamemente',
 'hidrogeniônicas',
 'semirreações',
 'chupanças',
 'bronzeamente',
 'lipossomo',
 'nanoemulsão',
 'triterpeno',
 'esrl',
 'ráficos',
 'eletrolisada',
 'antiumectante',
 'portalsaude',
 'trituramento',
 'lqes',
 'planetaorganico',
 'enertrag',
 'moreirajr',
 'hmáx',
 'hmín',
 'futurambiental',
 'heterozigóticas',
 'concregrama',
 'pisograma',
 'enólica',
 'semirreação',
 'wustita',
 'portaldaretina',
 'capsorubina',
 'criptoxantina',
 'dissubstituídas',
 'metilprop',
 'monossubstituídas',
 'pergaminácea',
 'calcosita',
 'nhch',
 'fácicas',
 'tetracloroguaiacol',
 'biorremediadores',
 'crapez',
 'krepsky',
 'sorventes',
 'bioabsorvível',
 'butanodioico',
 'hexanodioico',
 'cnptia',
 'sistemasdeproducao',
 'ciencianews',
 'handymath',
 'bachur',
 'trimetilxantina',
 'equimolares',
 'àquele',
 'temperaturaambiente',
 'sintonizarmos',
 'enxaguá',
 'fotocromática']

In [ ]:
cleaned_data['vetor_enunciado'] = lista_enunciados

In [ ]:
cleaned_data.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,ano,enunciado_limpo,alternativas_limpo,vetor_enunciado
0,91,Para realizar o desentupimento de tubulações d...,A: Al; B: Co; C: Cu(OH)2; D: Fe(OH)2; E: Pb,1.13773,A,2019,adicionada aumentando aumentar básico calor co...,A: al; B: co; C: cu oh; D: fe oh; E: pb,"[[-0.192243, -0.234884, -0.190927, -0.201125, ..."
1,92,As redes de alta tensão para transmissão de en...,A: Fazer o aterramento dos arames da cerca.; B...,1.45214,A,2019,alta animais aproximarem arame campo cerca cer...,A: arames aterramento cerca fazer; B: acrescen...,"[[-0.078058, -0.390552, -0.379023, 0.086376, 0..."
2,93,A esquistossomose (barriga-dʼágua) caracteriza...,A: impedir a penetração do parasita pela pele....,0.58402,E,2019,anticorpos após barriga baseia baço biomphalar...,A: impedir parasita pele penetração; B: caramu...,"[[0.202009, -0.377567, -0.509075, -0.0262, -0...."
3,94,"Em 1962, um jingle (vinheta musical) criado po...",A: Aquecer a casa e os corpos.; B: Evitar a en...,0.41535,C,2019,abriria animado apesar aquecer associar batia ...,A: aquecer casa corpos; B: casa corpos entrada...,"[[-0.203611, 0.159881, 0.093636, -0.080348, -0..."
4,95,Glicólise é um processo que ocorre nas células...,A: libera 112 kJ por mol de glicose.; B: liber...,2.21432,A,2019,alguns anaeróbico casos combustão completament...,A: glicose kj libera mol; B: glicose kj libera...,"[[-0.000374, -0.127046, -0.401209, -0.020222, ..."

In [ ]:
len(cleaned_data['vetor_enunciado'])

670

In [ ]:
vetores_medios_total = [] #vetor para armazenar o vetor de médias de cada enunciado

for i_enum in range(len(cleaned_data)):
  media_enum = [0]*len(cleaned_data['vetor_enunciado'][i_enum][0]) #cria um vetor inicial com todos valores iguais a zero
  for j_palavra in cleaned_data['vetor_enunciado'][i_enum]:
    media_enum = list(map(add, media_enum, j_palavra)) #adiciona os elementos de mesma posição de todos os vetores de palavras do enunciado
  media_enum = [x / len(cleaned_data['vetor_enunciado'][i_enum]) for x in media_enum] #divide todos os valores pelo número de palavras no enunciado
  vetores_medios_total.append(list(media_enum))

In [ ]:
len(vetores_medios_total[0])

300

In [ ]:
type(vetores_medios_total[0])

list

In [ ]:
cleaned_data['vetor_media'] = vetores_medios_total
cleaned_data.head(3)

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,ano,enunciado_limpo,alternativas_limpo,vetor_enunciado,vetor_media
0,91,Para realizar o desentupimento de tubulações d...,A: Al; B: Co; C: Cu(OH)2; D: Fe(OH)2; E: Pb,1.13773,A,2019,adicionada aumentando aumentar básico calor co...,A: al; B: co; C: cu oh; D: fe oh; E: pb,"[[-0.192243, -0.234884, -0.190927, -0.201125, ...","[0.026007884853454524, -0.027820302325105944, ..."
1,92,As redes de alta tensão para transmissão de en...,A: Fazer o aterramento dos arames da cerca.; B...,1.45214,A,2019,alta animais aproximarem arame campo cerca cer...,A: arames aterramento cerca fazer; B: acrescen...,"[[-0.078058, -0.390552, -0.379023, 0.086376, 0...","[-0.040842513768718794, 0.016304127806320023, ..."
2,93,A esquistossomose (barriga-dʼágua) caracteriza...,A: impedir a penetração do parasita pela pele....,0.58402,E,2019,anticorpos após barriga baseia baço biomphalar...,A: impedir parasita pele penetração; B: caramu...,"[[0.202009, -0.377567, -0.509075, -0.0262, -0....","[0.025191860097836246, -0.05666966698736998, 0..."

In [ ]:
#cleaned_data.to_csv('/content/drive/MyDrive/MED-enem/cleaned_data_vectors.csv')

In [ ]:
#cleaned_data.to_pickle('/content/drive/MyDrive/MED-enem/cleaned_data_vectors.pkl')

###Vetorização das alternativas

In [ ]:
cleaned_data = pd.read_pickle("/content/drive/MyDrive/MED-enem/cleaned_data_vectors.pkl")
cleaned_data.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,ano,enunciado_limpo,alternativas_limpo,vetor_enunciado,vetor_media
0,91,Para realizar o desentupimento de tubulações d...,A: Al; B: Co; C: Cu(OH)2; D: Fe(OH)2; E: Pb,1.13773,A,2019,adicionada aumentando aumentar básico calor co...,A: al; B: co; C: cu oh; D: fe oh; E: pb,"[[-0.192243, -0.234884, -0.190927, -0.201125, ...","[0.026007884853454524, -0.027820302325105944, ..."
1,92,As redes de alta tensão para transmissão de en...,A: Fazer o aterramento dos arames da cerca.; B...,1.45214,A,2019,alta animais aproximarem arame campo cerca cer...,A: arames aterramento cerca fazer; B: acrescen...,"[[-0.078058, -0.390552, -0.379023, 0.086376, 0...","[-0.040842513768718794, 0.016304127806320023, ..."
2,93,A esquistossomose (barriga-dʼágua) caracteriza...,A: impedir a penetração do parasita pela pele....,0.58402,E,2019,anticorpos após barriga baseia baço biomphalar...,A: impedir parasita pele penetração; B: caramu...,"[[0.202009, -0.377567, -0.509075, -0.0262, -0....","[0.025191860097836246, -0.05666966698736998, 0..."
3,94,"Em 1962, um jingle (vinheta musical) criado po...",A: Aquecer a casa e os corpos.; B: Evitar a en...,0.41535,C,2019,abriria animado apesar aquecer associar batia ...,A: aquecer casa corpos; B: casa corpos entrada...,"[[-0.203611, 0.159881, 0.093636, -0.080348, -0...","[-0.006095098719621698, 0.023178725284250343, ..."
4,95,Glicólise é um processo que ocorre nas células...,A: libera 112 kJ por mol de glicose.; B: liber...,2.21432,A,2019,alguns anaeróbico casos combustão completament...,A: glicose kj libera mol; B: glicose kj libera...,"[[-0.000374, -0.127046, -0.401209, -0.020222, ...","[-0.0031903900146461658, 0.002256707901634821,..."

In [ ]:
vetor = cleaned_data['vetor_enunciado'][0][0]
vetor

array([-0.192243, -0.234884, -0.190927, -0.201125, -0.039329,  0.172893,
        0.277837, -0.12796 ,  0.088521, -0.151292, -0.273545, -0.035119,
        0.086873, -0.107758, -0.120193,  0.027043,  0.243191,  0.06756 ,
       -0.298356, -0.275164, -0.186084, -0.021973, -0.09703 ,  0.517328,
        0.092161, -0.008722, -0.095655, -0.146118,  0.195674,  0.008202,
        0.063079, -0.020973, -0.193532, -0.261609, -0.015741, -0.178504,
       -0.183431,  0.012236, -0.247967,  0.167348,  0.160103, -0.114266,
       -0.167672, -0.037353,  0.064407,  0.111873,  0.116945, -0.159231,
       -0.119422,  0.170143, -0.063642, -0.039858,  0.105491, -0.068436,
        0.434969,  0.067126, -0.157407, -0.078119, -0.185272,  0.058469,
        0.024308, -0.264104,  0.164294, -0.292486,  0.178483,  0.110749,
       -0.158732, -0.077038,  0.076795,  0.004294,  0.019093, -0.125857,
       -0.119234, -0.187346, -0.118581,  0.100057,  0.010704,  0.28038 ,
        0.00077 ,  0.04011 , -0.023886, -0.054549,  0.226515, -0.064118,
        0.152837, -0.105814,  0.145027, -0.132862,  0.362789,  0.429921,
       -0.258208,  0.129271, -0.509697, -0.068767,  0.033735, -0.195297,
        0.13091 ,  0.182667, -0.256423,  0.186064, -0.095019,  0.415466,
        0.110745,  0.351292,  0.097766,  0.293068,  0.36969 , -0.154364,
       -0.488456, -0.041942,  0.191316, -0.059216,  0.126117,  0.221179,
        0.344706, -0.186725,  0.020596, -0.324777,  0.410606,  0.300507,
       -0.081567,  0.127029, -0.101706, -0.323933, -0.069618, -0.405199,
        0.464962,  0.077567,  0.285516,  0.365102,  0.011392, -0.214911,
       -0.142293, -0.03081 , -0.089593, -0.213054,  0.185933, -0.158173,
       -0.232901,  0.362183, -0.034819,  0.255647, -0.098115,  0.260404,
       -0.129636,  0.02258 , -0.053255,  0.037685, -0.056646,  0.231766,
       -0.170459,  0.23684 ,  0.311134, -0.091643,  0.009141,  0.394265,
       -0.25312 , -0.160851,  0.064153,  0.004332, -0.137113, -0.074566,
        0.013618,  0.153255, -0.068843,  0.114294, -0.404648,  0.276831,
        0.229105,  0.004698,  0.174717, -0.13845 , -0.053896, -0.007802,
       -0.298471,  0.077372,  0.044491,  0.019999,  0.052619,  0.47276 ,
       -0.176812,  0.271236,  0.134528,  0.002783, -0.043278, -0.057527,
        0.184873,  0.101113,  0.27955 ,  0.104116,  0.138214,  0.175303,
       -0.088193,  0.060037,  0.271654,  0.088519, -0.091604,  0.086465,
       -0.147387,  0.001815, -0.348311,  0.119234,  0.132989, -0.04066 ,
       -0.365334,  0.116045,  0.217931, -0.2174  ,  0.120538, -0.043334,
       -0.003161, -0.093465,  0.094338, -0.084987,  0.462483,  0.023116,
        0.029142,  0.097727,  0.089   , -0.075799, -0.087983,  0.084733,
       -0.040674,  0.432168, -0.176195,  0.123704, -0.053654,  0.100868,
        0.041612, -0.045016, -0.394074, -0.644184, -0.364244, -0.252483,
        0.167096,  0.148156, -0.18777 ,  0.159244,  0.249108, -0.079026,
        0.207416,  0.144976, -0.407039, -0.016255, -0.093218,  0.068678,
        0.135903, -0.050383,  0.065092, -0.094841,  0.134213, -0.242547,
        0.059162, -0.002037, -0.007872, -0.237133, -0.0067  , -0.398443,
        0.144667, -0.174249, -0.129647, -0.312405, -0.177736, -0.290291,
        0.136404, -0.021622, -0.092477, -0.116768,  0.119328,  0.065438,
        0.100424, -0.077321, -0.184915, -0.002897,  0.05981 ,  0.052285,
       -0.225164,  0.080017, -0.129254, -0.093229,  0.106906, -0.030134,
        0.062122,  0.160551, -0.034543,  0.014186, -0.057087,  0.328327,
       -0.267175,  0.197769, -0.344064, -0.242692,  0.023492,  0.188141,
       -0.008428, -0.031718, -0.021129, -0.223502, -0.070261,  0.230443],
      dtype=float32)

In [ ]:
lista_textos = []

for i in range(len(cleaned_data)):
  #divide a string entre as 5 alternativas
  if pd.isna(cleaned_data['alternativas_limpo'][i]):
    print(i)
  else:
    lista_alternativas = cleaned_data['alternativas_limpo'][i].split(';')
    textos = []
    #divide a letra da alternativa do texto
    for item in lista_alternativas:
      item_dividido = item.split(':')
      textos.append(item_dividido[1])
  lista_textos.append(textos)

22
46
131
147
410
413
423
427
442
444
455
460
466
473
478
643
644

In [ ]:
lista_textos[:3]

[[' al', ' co', ' cu oh', ' fe oh', ' pb'],
 [' arames aterramento cerca fazer',
  ' acrescentar cerca fusível segurança',
  ' alta aterramento realizar rede tensão',
  ' alta fusível instalar rede segurança tensão',
  ' alta encapados fios isolante rede tensão utilizar'],
 [' impedir parasita pele penetração',
  ' caramujo contágio eliminar',
  ' acesso especificamente esquistossomo fígado impedir',
  ' antes contato eliminar esquistossomo ocorra organismo',
  ' antes dentro eliminar esquistossomo manifestação organismo sintomas']]

In [ ]:
remover_palavras=[] #vetor de palavras que não compoem o corpus do modelo
enunciado_limpo_novo = [] #lista de palavras presentes na alternativa depois de limpa
lista_enunciados = [] #lista de alternativas vetorizadas

for i in lista_textos:
  alternativa_vet =[] #lista para armazenar os vetores de todas as palavras de uma alternativa

  for alternativa in i:
    alt = alternativa.split()
    #remove as palavras que não estão no corpus
    for palavra in remover_palavras:
      if palavra in alt:
        alt = [x for x in alt if x != palavra]

    for palavra in alt:
      if palavra.lower() in model:
        enunciado_vet.append(model[palavra.lower()])
      else:
        remover_palavras.append(palavra)

###Vetorização enunciados (ledor)

In [ ]:
cleaned_data = pd.read_csv("/content/drive/MyDrive/MED-enem/cleaned_data_ledor.csv")
cleaned_data.head(3)

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,year,enunciado_limpo,alternativas_limpo
0,1,A atmosfera terrestre é composta pelos gases n...,A: reduzir o calor irradiado pela Terra median...,-1.70677,C,2009,absorver acontece alternativa anos aquecendo a...,A: calor industrialização irradiado mediante p...
1,2,Analise a figura. Supondo que seja necessário ...,A: Concentração média de álcool no sangue ao l...,0.62043,D,2009,alternativa analise dar figura melhor necessár...,A: concentração dia longo média sangue álcool;...
2,3,Estima-se que haja atualmente no mundo 40 milh...,"A: induzir a imunidade, para proteger o organi...",2.07704,A,2009,acompanhamento aids antiviral atualmente caren...,A: contaminação imunidade induzir organismo pr...

In [ ]:
cleaned_data[cleaned_data.isnull().any(axis=1)]

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,year,enunciado_limpo,alternativas_limpo
137,55,O mecanismo que permite articular uma porta (d...,A; B; C; D; E,2.17000,D,2012,acesso articulada articular diagrama dobradiça...,NaN
142,60,Para melhorar a mobilidade urbana na rede metr...,A; B; C; D; E,1.31500,C,2012,aceleração administração adotou cidade constan...,NaN
148,66,O benzeno é um hidrocarboneto aromático presen...,A; B; C; D; E,2.31100,A,2012,adição altamente anemia apresentada aromático ...,NaN
155,73,Para ligar ou desligar uma mesma lâmpada a par...,A; B; C; D; E,2.33600,E,2012,chave circuito conecta conectam conforme conhe...,NaN
160,78,Os freios ABS são uma importante medida de seg...,A; B; C; D; E,1.58300,A,2012,abs acionado aplicada at atrito carro carros c...,NaN
182,55,A pílula anticoncepcional é um dos métodos con...,A; B; C; D; E,3.07540,A,2013,analisado anticoncepcional basicamente comprim...,NaN
185,58,"O citral, substância de odor fortemente cítric...",A; B; C; D; E,2.33270,A,2013,abelhas algumas alifática alta apis aplicações...,NaN
195,68,O glifosato (C3 H8 NO5 P) é um herbicida perte...,A; B; C; D; E,1.90070,B,2013,amino aminometilfosfônico ampa apresentados ca...,NaN
199,72,Um eletricista analisa o diagrama de uma insta...,A; B; C; D; E,2.03080,E,2013,ambiente amperímetros analisa aplicada conform...,NaN
214,87,"Em um dia sem vento, ao saltar de um avião, um...",A; B; C; D; E,2.16570,B,2013,aberto abertura algum após aterrissagem atingi...,NaN
216,89,Aquecedores solares usados em residências têm ...,"A 0,111.; B 0,125.; C 0,357.; D 0,428.; E 0,833.",1.84990,B,2013,ambiente aquecedores aquecida banho c deve ele...,NaN
234,64,O pêndulo de Newton pode ser constituído por c...,A; B; C; D; E,2.10244,C,2014,após cinco colidindo colisão constituído dado ...,NaN
235,65,"A forma das moléculas, como representadas no p...",A; B; C; D; E,2.36697,A,2014,ativa bioatividade biologicamente contendo des...,NaN

In [ ]:
remover_palavras=[] #vetor de palavras que não compoem o corpus do modelo
enunciado_limpo_novo = [] #lista de palavras presentes no enunciado depois de limpo
remover = [',', '.', ':', ';', '(', ')'] #lista de caracteres específicos a serem retirados
lista_enunciados = [] #lista de enunciados vetorizados

for indice in range(len(cleaned_data['enunciado_limpo'])):
  #print(indice)
  enunciado_vet =[] #lista para armazenar os vetores de todas as palavras de um enunciado
  enunciado = cleaned_data['enunciado_limpo'][indice].split()

  #remove as palavras que não estão no corpus
  for palavra in remover_palavras:
    if palavra in enunciado:
      enunciado = [x for x in enunciado if x != palavra]

  for palavra in enunciado:
    #remove os caracteres indesejados
    for i in remover:
      palavra = palavra.replace(i, "")

    if palavra.lower() in model:
      enunciado_vet.append(model[palavra.lower()])
    else:
      remover_palavras.append(palavra)

    #enunciado_vet.append(model[palavra.lower()])
  lista_enunciados.append(enunciado_vet)

In [ ]:
cleaned_data['vetor_enunciado'] = lista_enunciados

In [ ]:
vetores_medios_total = [] #vetor para armazenar o vetor de médias de cada enunciado

for i_enum in range(len(cleaned_data)):
  media_enum = [0]*len(cleaned_data['vetor_enunciado'][i_enum][0]) #cria um vetor inicial com todos valores iguais a zero
  for j_palavra in cleaned_data['vetor_enunciado'][i_enum]:
    media_enum = list(map(add, media_enum, j_palavra)) #adiciona os elementos de mesma posição de todos os vetores de palavras do enunciado
  media_enum = [x / len(cleaned_data['vetor_enunciado'][i_enum]) for x in media_enum] #divide todos os valores pelo número de palavras no enunciado
  vetores_medios_total.append(list(media_enum))

In [ ]:
cleaned_data['vetor_media'] = vetores_medios_total
cleaned_data.head(3)

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,year,enunciado_limpo,alternativas_limpo,vetor_enunciado,vetor_media
0,1,A atmosfera terrestre é composta pelos gases n...,A: reduzir o calor irradiado pela Terra median...,-1.70677,C,2009,absorver acontece alternativa anos aquecendo a...,A: calor industrialização irradiado mediante p...,"[[-0.072753, 0.136878, 0.160618, -0.442716, -0...","[0.016323044885853854, -0.032005971771842966, ..."
1,2,Analise a figura. Supondo que seja necessário ...,A: Concentração média de álcool no sangue ao l...,0.62043,D,2009,alternativa analise dar figura melhor necessár...,A: concentração dia longo média sangue álcool;...,"[[0.184257, -0.035359, 0.075923, 0.163333, -0....","[-0.0381658197465268, -0.027103909206661312, 0..."
2,3,Estima-se que haja atualmente no mundo 40 milh...,"A: induzir a imunidade, para proteger o organi...",2.07704,A,2009,acompanhamento aids antiviral atualmente caren...,A: contaminação imunidade induzir organismo pr...,"[[-0.117196, 0.170721, 0.426886, -0.014566, 0....","[0.0118313719691752, 0.012745790416374803, 0.0..."

In [ ]:
cleaned_data.to_pickle('/content/drive/MyDrive/MED-enem/cleaned_data_ledor_vectors.pkl')