#7. Modelos de Regressão

Este notebook explora diferentes modelos de regressão para análise de dados, incluindo Regressão Linear e Lasso, utilizando técnicas de pré-processamento como transformação Box-Cox e seleção de variáveis. O objetivo é avaliar o desempenho dos modelos em termos de métricas como RMSE e R², tanto nos datasets completos quanto após a remoção de outliers das questões do Enem (vetorizadas).

In [ ]:
# Importando Dependências para Modelos de Regressão
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import statsmodels.api as sm

from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error
from sklearn.linear_model import Lasso, LassoCV
#import scipy

In [ ]:
# Leitura dos dados
enem_data = pd.read_pickle("../data/final/enem_data_embeddings.pkl")
enem_data.head()

---

## 6.1. Regressão Linear - 300 dimensões

### 6.1.1. Dataset Completo

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data["enunciado_embbedings_word2vec"]]
y = enem_data["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min()*(-1))+1]*len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

0.6375985567450835

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
# Adicionando constante
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

In [ ]:
# Criando o modelo e realizando predição
model = sm.OLS(y_train, X_train).fit()
pred = model.predict(X_test)

In [ ]:
# Cálculo do RMSE
rms = root_mean_squared_error(y_test, pred)
print('RMSE', rms)

RMSE 1.0504498350168308

In [ ]:
# Visualização do modelo e resultados
print(model.summary(alpha=0.05))

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.710
Model:                            OLS   Adj. R-squared:                  0.110
Method:                 Least Squares   F-statistic:                     1.184
Date:                Thu, 22 May 2025   Prob (F-statistic):              0.125
Time:                        19:27:35   Log-Likelihood:                -80.002
No. Observations:                 446   AIC:                             762.0
Df Residuals:                     145   BIC:                             1996.
Df Model:                         300
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.8570      0.941      3.037      0.003       0.998       4.716
x1             0.1263      1.902      0.066      0.947      -3.633       3.885
x2             3.6873      1.929      1.912      0.058      -0.125       7.500
x3             0.4764      1.913      0.249      0.804      -3.305       4.257
x4             2.2703      1.762      1.289      0.200      -1.212       5.752
x5            -1.0427      1.664     -0.627      0.532      -4.331       2.246
x6            -4.3913      1.706     -2.574      0.011      -7.763      -1.020
x7            -1.2587      1.811     -0.695      0.488      -4.838       2.321
x8             2.3374      2.192      1.066      0.288      -1.995       6.670
x9             2.6829      1.982      1.354      0.178      -1.234       6.600
x10           -1.9863      1.843     -1.078      0.283      -5.629       1.656
x11            3.5860      1.832      1.957      0.052      -0.036       7.208
x12            1.1219      1.801      0.623      0.534      -2.437       4.681
x13            0.6552      2.019      0.325      0.746      -3.335       4.646
x14           -2.0082      1.911     -1.051      0.295      -5.786       1.769
x15           -0.9498      1.682     -0.565      0.573      -4.275       2.376
x16            2.0766      1.935      1.073      0.285      -1.749       5.902
x17           -0.7489      1.779     -0.421      0.674      -4.265       2.768
x18            1.0092      1.844      0.547      0.585      -2.635       4.653
x19           -0.3703      1.784     -0.208      0.836      -3.897       3.156
x20           -0.1119      2.010     -0.056      0.956      -4.084       3.860
x21            1.3587      1.801      0.754      0.452      -2.201       4.918
x22            1.5091      1.899      0.795      0.428      -2.244       5.262
x23           -2.6917      2.169     -1.241      0.217      -6.978       1.595
x24            0.7260      1.966      0.369      0.713      -3.161       4.613
x25           -3.7961      1.783     -2.129      0.035      -7.320      -0.273
x26            1.2403      1.948      0.637      0.525      -2.609       5.090
x27            0.6154      1.895      0.325      0.746      -3.131       4.362
x28           -0.5488      1.949     -0.282      0.779      -4.401       3.303
x29           -2.5465      2.004     -1.270      0.206      -6.508       1.415
x30           -2.1532      1.936     -1.112      0.268      -5.980       1.673
x31            0.5987      1.948      0.307      0.759      -3.252       4.450
x32           -0.6912      1.982     -0.349      0.728      -4.608       3.226
x33            0.5073      1.700      0.298      0.766      -2.853       3.867
x34           -5.2401      1.917     -2.733      0.007      -9.029      -1.451
x35           -1.3915      1.887     -0.738      0.462      -5.120       2.337
x36           -4.3603      2.009     -2.171      0.032      -8.330      -0.390
x37            1.3812      1.875      0.737      0.463      -2.325       5.088
x38            1.1167      1.895      0.589      0.557      -2.629       4.863
x39           -0.3378      1.934     -0.175      0.862      -4.161       3.485
x40            2.2480      1.806      1.244      0.215      -1.322       5.818
x41            2.7758      1.861      1.491      0.138      -0.903       6.455
x42           -0.0467      2.129     -0.022      0.983      -4.255       4.161
x43           -0.3989      1.748     -0.228      0.820      -3.853       3.055
x44           -1.4534      1.915     -0.759      0.449      -5.239       2.332
x45           -1.0395      2.157     -0.482      0.631      -5.302       3.223
x46            0.6979      1.685      0.414      0.679      -2.633       4.029
x47           -1.9765      1.958     -1.010      0.314      -5.846       1.893
x48            3.4138      1.847      1.848      0.067      -0.238       7.065
x49            2.5788      2.025      1.274      0.205      -1.423       6.581
x50           -0.2945      1.891     -0.156      0.876      -4.032       3.443
x51            1.4558      1.801      0.808      0.420      -2.104       5.016
x52            0.2851      1.960      0.145      0.885      -3.590       4.160
x53            2.9686      1.956      1.518      0.131      -0.897       6.834
x54            0.5723      2.256      0.254      0.800      -3.887       5.032
x55            0.2031      1.870      0.109      0.914      -3.493       3.899
x56            2.5975      1.942      1.337      0.183      -1.241       6.436
x57           -2.7362      2.022     -1.353      0.178      -6.732       1.260
x58           -3.5182      2.057     -1.710      0.089      -7.584       0.547
x59           -5.4029      1.957     -2.761      0.007      -9.271      -1.535
x60           -1.1341      1.904     -0.596      0.552      -4.898       2.630
x61            0.2778      1.775      0.156      0.876      -3.231       3.786
x62            2.1780      1.836      1.186      0.238      -1.452       5.808
x63           -1.8294      1.832     -0.999      0.320      -5.449       1.791
x64           -4.5516      2.007     -2.267      0.025      -8.519      -0.584
x65            0.9824      1.969      0.499      0.619      -2.908       4.873
x66            0.6182      1.786      0.346      0.730      -2.912       4.148
x67            5.1583      2.092      2.465      0.015       1.023       9.294
x68            5.0771      2.045      2.483      0.014       1.035       9.119
x69            0.2038      2.006      0.102      0.919      -3.760       4.168
x70            1.0020      1.997      0.502      0.617      -2.944       4.949
x71            2.9605      1.881      1.574      0.118      -0.758       6.679
x72           -1.9096      1.983     -0.963      0.337      -5.829       2.010
x73           -1.3933      1.853     -0.752      0.453      -5.055       2.268
x74           -2.0123      1.886     -1.067      0.288      -5.740       1.715
x75            2.7156      1.958      1.387      0.168      -1.154       6.585
x76            3.1765      1.781      1.784      0.077      -0.343       6.696
x77           -0.5416      1.929     -0.281      0.779      -4.353       3.270
x78           -2.2192      1.957     -1.134      0.259      -6.087       1.649
x79           -2.2642      2.007     -1.128      0.261      -6.230       1.702
x80           -1.8984      1.832     -1.036      0.302      -5.520       1.723
x81           -0.0321      1.791     -0.018      0.986      -3.572       3.508
x82            2.2087      1.864      1.185      0.238      -1.476       5.894
x83            1.7979      1.903      0.945      0.346      -1.962       5.558
x84           -1.4770      2.238     -0.660      0.510      -5.900       2.945
x85           -0.3942      2.254     -0.175      0.861      -4.849       4.060
x86            3.0193      1.975      1.529      0.129      -0.885       6.923
x87           -3.4420      1.837     -1.874      0.063      -7.073       0.189
x88           -3.1729      2.279     -1.392      0.166      -7.677       1.331
x89           -3.6515      1.854     -1.970      0.051      -7.316       0.013
x90           -1.8056      1.853     -0.974      0.332      -5.468       1.857
x91            2.1582      1.907      1.132      0.260      -1.611       5.927
x92            2.8582      1.918      1.491      0.138      -0.932       6.648
x93           -2.7558      1.837     -1.500      0.136      -6.387       0.875
x94           -0.5554      2.042     -0.272      0.786      -4.591       3.480
x95            1.4790      1.840      0.804      0.423      -2.159       5.117
x96           -1.9613      2.115     -0.928      0.355      -6.141       2.218
x97           -3.4191      1.879     -1.820      0.071      -7.133       0.295
x98           -0.2514      2.188     -0.115      0.909      -4.576       4.073
x99           -1.8534      2.232     -0.830      0.408      -6.265       2.559
x100          -2.1423      2.011     -1.065      0.288      -6.116       1.832
x101          -2.1497      1.958     -1.098      0.274      -6.019       1.719
x102           2.0951      2.015      1.040      0.300      -1.888       6.078
x103          -2.2605      1.859     -1.216      0.226      -5.935       1.414
x104          -0.8017      1.968     -0.407      0.684      -4.692       3.088
x105          -1.6587      2.022     -0.820      0.413      -5.654       2.337
x106           3.9345      1.893      2.079      0.039       0.194       7.675
x107           2.6236      1.874      1.400      0.164      -1.080       6.327
x108           5.6443      1.946      2.901      0.004       1.798       9.490
x109          -1.1089      1.956     -0.567      0.572      -4.975       2.758
x110          -3.0833      1.948     -1.583      0.116      -6.933       0.767
x111          -3.5182      1.801     -1.953      0.053      -7.078       0.042
x112          -3.8060      1.963     -1.939      0.054      -7.686       0.074
x113          -3.0503      1.765     -1.728      0.086      -6.539       0.438
x114           2.1522      2.086      1.032      0.304      -1.971       6.275
x115          -1.6502      1.800     -0.917      0.361      -5.208       1.907
x116           4.0004      1.974      2.027      0.045       0.099       7.902
x117          -1.8728      1.795     -1.044      0.298      -5.420       1.674
x118           0.0310      2.146      0.014      0.988      -4.210       4.272
x119          -0.8097      1.881     -0.430      0.668      -4.528       2.908
x120           3.4184      2.177      1.570      0.119      -0.884       7.721
x121           0.9421      2.076      0.454      0.651      -3.162       5.046
x122           1.3078      2.053      0.637      0.525      -2.751       5.366
x123           1.2768      1.959      0.652      0.516      -2.595       5.149
x124           0.3189      1.799      0.177      0.860      -3.238       3.876
x125          -0.4981      2.023     -0.246      0.806      -4.496       3.500
x126          -0.9552      1.935     -0.494      0.622      -4.779       2.868
x127          -0.6685      1.911     -0.350      0.727      -4.445       3.108
x128           0.4784      1.936      0.247      0.805      -3.348       4.304
x129          -6.4023      1.981     -3.232      0.002     -10.317      -2.487
x130          -4.2132      2.314     -1.821      0.071      -8.787       0.361
x131          -4.2642      2.082     -2.049      0.042      -8.378      -0.150
x132           0.0762      1.793      0.042      0.966      -3.468       3.620
x133          -2.1148      1.930     -1.096      0.275      -5.929       1.699
x134          -2.5549      1.936     -1.320      0.189      -6.380       1.271
x135          -2.4357      1.932     -1.261      0.209      -6.254       1.383
x136          -2.8146      2.013     -1.398      0.164      -6.793       1.164
x137           1.2591      1.930      0.652      0.515      -2.555       5.073
x138           0.3248      2.108      0.154      0.878      -3.842       4.491
x139          -0.4656      2.027     -0.230      0.819      -4.472       3.541
x140          -4.1196      1.832     -2.249      0.026      -7.741      -0.499
x141           0.4352      1.919      0.227      0.821      -3.357       4.228
x142           0.5468      1.877      0.291      0.771      -3.164       4.257
x143           0.1718      1.782      0.096      0.923      -3.350       3.693
x144           0.2125      2.138      0.099      0.921      -4.013       4.438
x145          -2.6180      2.084     -1.256      0.211      -6.736       1.500
x146           4.8345      2.138      2.262      0.025       0.610       9.059
x147           0.3490      2.097      0.166      0.868      -3.795       4.493
x148          -0.1262      1.999     -0.063      0.950      -4.076       3.824
x149          -2.3367      1.875     -1.246      0.215      -6.042       1.369
x150           0.8441      1.796      0.470      0.639      -2.705       4.394
x151           0.0726      1.927      0.038      0.970      -3.737       3.882
x152          -1.5578      1.955     -0.797      0.427      -5.422       2.307
x153          -1.2120      2.282     -0.531      0.596      -5.722       3.298
x154           0.9479      1.726      0.549      0.584      -2.463       4.358
x155          -0.7138      2.055     -0.347      0.729      -4.776       3.349
x156          -3.6891      1.823     -2.024      0.045      -7.291      -0.087
x157           1.6247      1.823      0.891      0.374      -1.978       5.227
x158           0.1944      1.693      0.115      0.909      -3.152       3.541
x159           2.1040      1.900      1.108      0.270      -1.650       5.858
x160          -1.3540      2.006     -0.675      0.501      -5.318       2.610
x161          -0.6980      2.135     -0.327      0.744      -4.917       3.521
x162          -0.0399      2.019     -0.020      0.984      -4.030       3.950
x163          -0.8944      1.727     -0.518      0.605      -4.308       2.519
x164           2.5223      2.151      1.172      0.243      -1.730       6.774
x165          -1.2825      1.912     -0.671      0.503      -5.061       2.496
x166          -0.6580      1.912     -0.344      0.731      -4.437       3.121
x167           0.7381      1.875      0.394      0.694      -2.968       4.445
x168           2.3611      2.013      1.173      0.243      -1.618       6.340
x169          -1.0497      1.797     -0.584      0.560      -4.602       2.502
x170           0.7773      1.901      0.409      0.683      -2.980       4.535
x171          -0.0153      1.970     -0.008      0.994      -3.908       3.878
x172          -1.4345      1.978     -0.725      0.469      -5.344       2.475
x173          -1.6661      1.905     -0.875      0.383      -5.432       2.099
x174          -1.8747      1.947     -0.963      0.337      -5.723       1.974
x175           0.9663      2.015      0.479      0.632      -3.017       4.950
x176          -6.5454      1.896     -3.453      0.001     -10.292      -2.799
x177          -0.5941      1.961     -0.303      0.762      -4.471       3.283
x178          -1.1427      1.637     -0.698      0.486      -4.378       2.093
x179          -0.3146      1.987     -0.158      0.874      -4.242       3.613
x180           4.5149      2.194      2.058      0.041       0.178       8.852
x181          -1.2618      1.858     -0.679      0.498      -4.935       2.411
x182          -0.3107      1.996     -0.156      0.877      -4.256       3.634
x183          -2.0314      1.977     -1.027      0.306      -5.939       1.877
x184           1.2590      1.921      0.655      0.513      -2.537       5.055
x185           4.0099      2.050      1.956      0.052      -0.042       8.062
x186          -0.0258      1.948     -0.013      0.989      -3.876       3.825
x187          -3.2605      2.118     -1.540      0.126      -7.446       0.925
x188          -0.4475      1.954     -0.229      0.819      -4.309       3.414
x189           1.0460      1.946      0.537      0.592      -2.801       4.893
x190           3.3199      1.896      1.751      0.082      -0.428       7.067
x191           0.2317      1.845      0.126      0.900      -3.416       3.879
x192           1.1848      1.848      0.641      0.523      -2.469       4.838
x193          -1.2922      1.983     -0.652      0.516      -5.211       2.627
x194          -2.3134      2.058     -1.124      0.263      -6.381       1.754
x195           0.3452      2.034      0.170      0.865      -3.675       4.366
x196          -6.9691      2.057     -3.387      0.001     -11.036      -2.903
x197          -5.6887      2.243     -2.536      0.012     -10.122      -1.255
x198           0.1208      1.784      0.068      0.946      -3.405       3.646
x199          -0.8408      1.930     -0.436      0.664      -4.655       2.973
x200           2.5401      1.696      1.497      0.136      -0.813       5.893
x201          -1.1112      1.816     -0.612      0.542      -4.701       2.478
x202          -1.4892      1.942     -0.767      0.444      -5.328       2.349
x203          -3.1829      2.062     -1.544      0.125      -7.258       0.892
x204          -0.7639      1.883     -0.406      0.686      -4.485       2.958
x205          -1.6072      1.826     -0.880      0.380      -5.216       2.001
x206          -3.0473      2.078     -1.466      0.145      -7.155       1.060
x207           2.7629      2.044      1.352      0.179      -1.277       6.803
x208           0.2024      1.928      0.105      0.917      -3.607       4.012
x209           1.4593      1.976      0.739      0.461      -2.446       5.365
x210          -1.2311      1.786     -0.689      0.492      -4.762       2.299
x211           3.1353      1.759      1.782      0.077      -0.342       6.613
x212           2.4097      1.812      1.330      0.186      -1.171       5.990
x213          -3.3115      2.070     -1.600      0.112      -7.403       0.780
x214          -3.2339      2.143     -1.509      0.133      -7.469       1.001
x215          -0.4728      2.064     -0.229      0.819      -4.552       3.606
x216          -0.9593      1.904     -0.504      0.615      -4.723       2.804
x217           1.9221      1.781      1.079      0.282      -1.599       5.443
x218           2.6841      2.005      1.339      0.183      -1.279       6.647
x219           0.3258      1.776      0.183      0.855      -3.185       3.837
x220          -2.0631      1.788     -1.154      0.250      -5.597       1.471
x221          -2.5883      2.199     -1.177      0.241      -6.935       1.758
x222          -2.0943      1.933     -1.083      0.280      -5.915       1.726
x223          -1.6623      1.926     -0.863      0.390      -5.470       2.145
x224           2.0915      1.941      1.078      0.283      -1.745       5.928
x225          -1.5454      1.737     -0.890      0.375      -4.978       1.887
x226           1.9008      2.066      0.920      0.359      -2.182       5.983
x227          -3.7241      1.958     -1.902      0.059      -7.593       0.145
x228          -0.8288      2.106     -0.393      0.695      -4.992       3.335
x229          -0.9540      1.884     -0.506      0.613      -4.677       2.769
x230           2.1518      1.725      1.248      0.214      -1.257       5.560
x231          -2.5714      1.693     -1.519      0.131      -5.918       0.775
x232           0.8746      2.025      0.432      0.666      -3.128       4.877
x233          -2.1846      1.886     -1.158      0.249      -5.912       1.543
x234           0.2997      1.711      0.175      0.861      -3.083       3.682
x235          -2.1134      1.830     -1.155      0.250      -5.731       1.504
x236          -2.2964      1.744     -1.317      0.190      -5.743       1.150
x237          -0.5561      2.046     -0.272      0.786      -4.599       3.487
x238           0.6757      2.006      0.337      0.737      -3.289       4.640
x239          -1.1863      1.826     -0.650      0.517      -4.795       2.422

### 6.1.3. Modelo com Corte (-3,3)

In [ ]:
enem_filtered = enem_data.copy()
enem_filtered = enem_filtered[
    (enem_filtered["dificuldade"] >= -3) & (enem_filtered["dificuldade"] <= 3)
]
enem_filtered["dificuldade"].describe()

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_filtered["enunciado_embbedings_word2vec"]]
y = enem_filtered["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min()*(-1))+1]*len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

1.7873995037544776

In [ ]:
# Dividindo os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
# Adicionando constante
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

In [ ]:
# Criando o modelo e realizando a predição
model = sm.OLS(y_train, X_train).fit()
pred = model.predict(X_test)

In [ ]:
# Cálculo do RMSE
rms = root_mean_squared_error(y_test, pred)
print("RMSE:", rms)

RMSE 4.048974956373059

In [ ]:
print(model.summary(alpha = 0.05))

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.759
Model:                            OLS   Adj. R-squared:                  0.217
Method:                 Least Squares   F-statistic:                     1.399
Date:                Thu, 22 May 2025   Prob (F-statistic):             0.0137
Time:                        19:27:35   Log-Likelihood:                -652.64
No. Observations:                 434   AIC:                             1907.
Df Residuals:                     133   BIC:                             3133.
Df Model:                         300
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.3232      4.078      1.060      0.291      -3.744      12.390
x1            -9.3473      7.598     -1.230      0.221     -24.377       5.682
x2            -6.1063      7.690     -0.794      0.429     -21.318       9.105
x3            -9.0119      7.886     -1.143      0.255     -24.611       6.587
x4            -1.7080      7.803     -0.219      0.827     -17.142      13.726
x5            13.1121      7.072      1.854      0.066      -0.875      27.100
x6             6.3821      7.175      0.889      0.375      -7.810      20.574
x7            -8.0312      7.214     -1.113      0.268     -22.301       6.239
x8           -13.2877      8.180     -1.624      0.107     -29.468       2.892
x9            -8.8833      8.357     -1.063      0.290     -25.414       7.647
x10           13.4911      8.268      1.632      0.105      -2.863      29.845
x11           15.0319      7.752      1.939      0.055      -0.302      30.366
x12            8.1949      7.169      1.143      0.255      -5.985      22.375
x13            7.1367      8.176      0.873      0.384      -9.036      23.309
x14           -1.6127      7.509     -0.215      0.830     -16.466      13.241
x15            4.2393      7.096      0.597      0.551      -9.796      18.274
x16           -9.4451      7.438     -1.270      0.206     -24.156       5.266
x17            7.5644      6.929      1.092      0.277      -6.140      21.269
x18           -4.8140      7.527     -0.640      0.524     -19.702      10.074
x19           -6.8752      8.301     -0.828      0.409     -23.294       9.544
x20            4.7507      7.400      0.642      0.522      -9.885      19.387
x21           -2.3258      7.179     -0.324      0.746     -16.525      11.874
x22          -12.6493      7.574     -1.670      0.097     -27.631       2.333
x23            5.3189      8.229      0.646      0.519     -10.957      21.595
x24           -6.9783      7.521     -0.928      0.355     -21.854       7.898
x25           -6.1345      7.741     -0.792      0.429     -21.446       9.177
x26            1.0794      7.103      0.152      0.879     -12.970      15.129
x27           -2.0319      7.622     -0.267      0.790     -17.108      13.044
x28           15.5631      8.190      1.900      0.060      -0.637      31.764
x29            9.7767      8.077      1.210      0.228      -6.200      25.753
x30          -22.4161      7.886     -2.843      0.005     -38.014      -6.818
x31           -3.3229      8.127     -0.409      0.683     -19.398      12.752
x32           -3.9290      9.066     -0.433      0.665     -21.861      14.003
x33           -6.6039      7.360     -0.897      0.371     -21.161       7.953
x34           -5.2002      7.975     -0.652      0.515     -20.975      10.574
x35            2.1353      8.050      0.265      0.791     -13.788      18.059
x36           -4.8355      7.450     -0.649      0.517     -19.572       9.901
x37            0.0892      7.342      0.012      0.990     -14.433      14.612
x38           -8.5117      7.834     -1.087      0.279     -24.006       6.983
x39           21.2606      8.217      2.587      0.011       5.008      37.513
x40           -1.3758      6.912     -0.199      0.843     -15.048      12.296
x41           14.3590      7.625      1.883      0.062      -0.723      29.441
x42           -5.8489      8.846     -0.661      0.510     -23.346      11.648
x43           -9.0171      7.875     -1.145      0.254     -24.594       6.560
x44           11.8298      8.091      1.462      0.146      -4.175      27.834
x45            5.7903      7.867      0.736      0.463      -9.769      21.350
x46            2.1740      6.935      0.313      0.754     -11.543      15.891
x47            3.7343      8.023      0.465      0.642     -12.135      19.604
x48            2.5978      7.083      0.367      0.714     -11.413      16.608
x49            1.3260      7.446      0.178      0.859     -13.402      16.054
x50           12.9827      7.622      1.703      0.091      -2.094      28.060
x51          -14.3540      7.795     -1.841      0.068     -29.773       1.065
x52           11.6098      8.038      1.444      0.151      -4.290      27.509
x53          -10.7275      8.278     -1.296      0.197     -27.100       5.645
x54           12.9845      9.248      1.404      0.163      -5.307      31.276
x55            9.9830      7.811      1.278      0.203      -5.466      25.432
x56            9.9754      7.860      1.269      0.207      -5.572      25.523
x57            1.1140      7.907      0.141      0.888     -14.525      16.753
x58            1.3567      9.003      0.151      0.880     -16.450      19.164
x59          -18.3442      7.750     -2.367      0.019     -33.674      -3.015
x60           19.7941      8.109      2.441      0.016       3.755      35.833
x61           -0.8272      7.262     -0.114      0.909     -15.191      13.536
x62            8.8210      8.072      1.093      0.276      -7.146      24.788
x63            4.6789      7.927      0.590      0.556     -11.000      20.358
x64           -3.7162      7.331     -0.507      0.613     -18.217      10.784
x65            4.7410      7.977      0.594      0.553     -11.037      20.519
x66          -10.3308      7.445     -1.388      0.168     -25.056       4.394
x67            5.5833      7.486      0.746      0.457      -9.223      20.389
x68           16.6960      8.231      2.028      0.045       0.416      32.976
x69          -14.1189      7.676     -1.839      0.068     -29.302       1.064
x70           -3.6902      8.053     -0.458      0.648     -19.618      12.238
x71           -2.7441      7.462     -0.368      0.714     -17.504      12.015
x72            4.1497      8.371      0.496      0.621     -12.407      20.706
x73           -6.8249      7.570     -0.902      0.369     -21.799       8.149
x74            5.3860      8.857      0.608      0.544     -12.132      22.904
x75           -2.7669      8.078     -0.343      0.732     -18.745      13.211
x76           17.1322      7.578      2.261      0.025       2.144      32.120
x77          -10.3505      7.318     -1.414      0.160     -24.826       4.125
x78           12.1942      7.881      1.547      0.124      -3.394      27.783
x79           -0.8498      7.495     -0.113      0.910     -15.675      13.975
x80            3.6851      7.580      0.486      0.628     -11.308      18.678
x81            9.0923      7.734      1.176      0.242      -6.206      24.391
x82           -5.3540      7.727     -0.693      0.490     -20.638       9.930
x83           -8.6655      8.050     -1.076      0.284     -24.588       7.257
x84            6.8779      9.022      0.762      0.447     -10.968      24.724
x85          -10.8641      9.383     -1.158      0.249     -29.422       7.694
x86            4.0623      6.994      0.581      0.562      -9.772      17.897
x87            5.4383      7.135      0.762      0.447      -8.675      19.551
x88          -13.5979      9.175     -1.482      0.141     -31.747       4.551
x89           -2.1349      7.919     -0.270      0.788     -17.799      13.529
x90            1.2255      7.606      0.161      0.872     -13.818      16.269
x91           -9.3652      7.821     -1.197      0.233     -24.835       6.105
x92            7.3875      7.704      0.959      0.339      -7.850      22.625
x93           -1.7280      7.492     -0.231      0.818     -16.548      13.092
x94           13.5291      7.536      1.795      0.075      -1.378      28.436
x95           10.8352      7.516      1.442      0.152      -4.031      25.701
x96           14.1093      8.483      1.663      0.099      -2.670      30.889
x97            0.9271      8.154      0.114      0.910     -15.201      17.055
x98          -20.0689      9.040     -2.220      0.028     -37.950      -2.188
x99          -13.2366      9.064     -1.460      0.147     -31.165       4.692
x100          13.7445      8.146      1.687      0.094      -2.367      29.856
x101           2.5727      7.599      0.339      0.735     -12.458      17.603
x102          10.2664      8.588      1.195      0.234      -6.721      27.254
x103          -4.1820      8.461     -0.494      0.622     -20.917      12.553
x104          10.1802      8.312      1.225      0.223      -6.260      26.620
x105           2.8627      7.481      0.383      0.703     -11.935      17.661
x106         -14.2780      7.333     -1.947      0.054     -28.782       0.226
x107           0.3031      6.901      0.044      0.965     -13.347      13.953
x108           8.5877      7.379      1.164      0.247      -6.008      23.184
x109           0.8373      8.707      0.096      0.924     -16.384      18.059
x110           1.8878      8.507      0.222      0.825     -14.940      18.715
x111           1.5678      7.781      0.201      0.841     -13.823      16.959
x112          -1.4660      8.138     -0.180      0.857     -17.564      14.632
x113          -2.5644      7.750     -0.331      0.741     -17.894      12.766
x114         -12.6848      8.714     -1.456      0.148     -29.922       4.552
x115           3.0444      8.362      0.364      0.716     -13.495      19.584
x116           3.8212      8.373      0.456      0.649     -12.741      20.383
x117           4.5496      7.266      0.626      0.532      -9.823      18.922
x118          -9.6196      9.259     -1.039      0.301     -27.934       8.695
x119           4.2687      7.320      0.583      0.561     -10.210      18.748
x120          11.7138      7.319      1.600      0.112      -2.764      26.191
x121          -5.7319      8.851     -0.648      0.518     -23.238      11.774
x122           2.1244      7.954      0.267      0.790     -13.608      17.856
x123          -2.1036      8.299     -0.253      0.800     -18.519      14.311
x124           0.3435      7.320      0.047      0.963     -14.134      14.821
x125           6.7868      7.531      0.901      0.369      -8.108      21.682
x126          -2.4645      7.103     -0.347      0.729     -16.513      11.584
x127          -4.9781      7.903     -0.630      0.530     -20.610      10.654
x128           4.6539      7.827      0.595      0.553     -10.827      20.135
x129         -20.8382      8.004     -2.603      0.010     -36.671      -5.006
x130           6.9749      8.263      0.844      0.400      -9.368      23.318
x131           1.0997      8.984      0.122      0.903     -16.669      18.869
x132          13.7651      7.751      1.776      0.078      -1.566      29.096
x133         -11.1895      7.743     -1.445      0.151     -26.505       4.126
x134          -5.8226      7.929     -0.734      0.464     -21.506       9.861
x135         -12.2614      8.006     -1.532      0.128     -28.097       3.574
x136           2.0337      7.993      0.254      0.800     -13.777      17.844
x137           1.9299      7.563      0.255      0.799     -13.029      16.889
x138          -5.6311      8.504     -0.662      0.509     -22.452      11.190
x139          -1.5896      7.811     -0.204      0.839     -17.040      13.860
x140         -13.4078      7.800     -1.719      0.088     -28.835       2.020
x141          -1.0397      8.563     -0.121      0.904     -17.977      15.898
x142           5.1636      8.109      0.637      0.525     -10.877      21.204
x143         -15.6253      7.634     -2.047      0.043     -30.725      -0.525
x144           3.7410      9.093      0.411      0.681     -14.246      21.728
x145          -6.4764      8.223     -0.788      0.432     -22.741       9.788
x146           8.5323      7.766      1.099      0.274      -6.829      23.893
x147          -6.0021      7.675     -0.782      0.436     -21.184       9.180
x148          -3.7850      7.769     -0.487      0.627     -19.152      11.582
x149          -3.0173      6.784     -0.445      0.657     -16.436      10.401
x150           5.7505      7.047      0.816      0.416      -8.188      19.689
x151           9.7394      7.878      1.236      0.219      -5.844      25.323
x152          -9.0613      7.785     -1.164      0.247     -24.460       6.338
x153          -1.7332      7.803     -0.222      0.825     -17.168      13.701
x154           2.5990      7.946      0.327      0.744     -13.117      18.315
x155           2.2514      7.711      0.292      0.771     -13.001      17.504
x156          -5.7087      7.302     -0.782      0.436     -20.151       8.733
x157          11.1613      7.561      1.476      0.142      -3.793      26.116
x158           1.1171      7.082      0.158      0.875     -12.890      15.125
x159         -14.1591      7.874     -1.798      0.074     -29.734       1.416
x160          -1.8545      8.294     -0.224      0.823     -18.260      14.551
x161          -8.9562      8.620     -1.039      0.301     -26.006       8.094
x162          14.3029      7.544      1.896      0.060      -0.618      29.224
x163          -9.0854      6.890     -1.319      0.190     -22.714       4.544
x164          -3.0807      8.156     -0.378      0.706     -19.212      13.051
x165           6.9245      7.717      0.897      0.371      -8.339      22.188
x166         -12.6636      8.541     -1.483      0.141     -29.558       4.231
x167           0.3839      7.917      0.048      0.961     -15.275      16.043
x168          -7.5881      7.816     -0.971      0.333     -23.047       7.871
x169           6.6214      8.371      0.791      0.430      -9.936      23.179
x170         -21.7652      8.016     -2.715      0.008     -37.620      -5.910
x171          14.2829      7.943      1.798      0.074      -1.427      29.993
x172           3.1062      7.813      0.398      0.692     -12.349      18.561
x173           6.6886      7.594      0.881      0.380      -8.331      21.709
x174         -11.9380      7.257     -1.645      0.102     -26.291       2.415
x175         -16.1040      7.545     -2.134      0.035     -31.028      -1.180
x176           0.0899      7.741      0.012      0.991     -15.221      15.401
x177           9.2399      8.527      1.084      0.281      -7.626      26.106
x178          11.1217      7.277      1.528      0.129      -3.271      25.515
x179          21.6239      8.571      2.523      0.013       4.670      38.578
x180          -0.4449      7.675     -0.058      0.954     -15.626      14.736
x181           4.7974      7.445      0.644      0.520      -9.928      19.522
x182         -19.7357      8.681     -2.274      0.025     -36.905      -2.566
x183           6.6530      8.760      0.760      0.449     -10.673      23.979
x184          10.6863      7.905      1.352      0.179      -4.950      26.322
x185          -3.9358      7.794     -0.505      0.614     -19.353      11.481
x186           0.4942      7.947      0.062      0.951     -15.224      16.212
x187         -13.6776      8.960     -1.527      0.129     -31.400       4.045
x188          14.6326      7.901      1.852      0.066      -0.994      30.260
x189          -9.4877      7.072     -1.342      0.182     -23.475       4.500
x190           5.7984      9.052      0.641      0.523     -12.106      23.703
x191          -9.5692      7.564     -1.265      0.208     -24.530       5.392
x192           9.3333      7.597      1.229      0.221      -5.693      24.360
x193          -0.3436      8.070     -0.043      0.966     -16.305      15.618
x194           7.9513      8.003      0.994      0.322      -7.879      23.781
x195           7.8813      8.160      0.966      0.336      -8.259      24.022
x196          -9.0599      8.355     -1.084      0.280     -25.585       7.465
x197          -5.9814      8.937     -0.669      0.504     -23.659      11.696
x198          -4.3878      8.389     -0.523      0.602     -20.981      12.206
x199           2.9211      7.937      0.368      0.713     -12.779      18.621
x200           9.9422      6.695      1.485      0.140      -3.299      23.184
x201           4.0405      6.878      0.587      0.558      -9.565      17.645
x202         -11.7671      8.487     -1.386      0.168     -28.554       5.020
x203         -14.6114      8.767     -1.667      0.098     -31.953       2.730
x204          -2.5057      8.401     -0.298      0.766     -19.122      14.111
x205         -13.1826      6.873     -1.918      0.057     -26.778       0.413
x206           3.6100      7.766      0.465      0.643     -11.751      18.971
x207          -4.6896      7.904     -0.593      0.554     -20.324      10.945
x208           1.7396      7.616      0.228      0.820     -13.325      16.804
x209          -3.3851      8.463     -0.400      0.690     -20.125      13.354
x210          18.2159      8.070      2.257      0.026       2.254      34.178
x211           5.3049      7.451      0.712      0.478      -9.433      20.043
x212          -4.9140      6.936     -0.708      0.480     -18.633       8.805
x213          -1.1256      8.030     -0.140      0.889     -17.008      14.757
x214         -15.1254      7.610     -1.988      0.049     -30.177      -0.074
x215          -1.6241      8.745     -0.186      0.853     -18.922      15.674
x216           3.2965      7.711      0.428      0.670     -11.955      18.548
x217           8.8933      7.031      1.265      0.208      -5.013      22.799
x218           1.7052      7.961      0.214      0.831     -14.041      17.452
x219           3.1538      7.121      0.443      0.659     -10.931      17.239
x220           2.9881      7.478      0.400      0.690     -11.803      17.779
x221         -20.6513      8.397     -2.459      0.015     -37.260      -4.043
x222          -3.2866      7.829     -0.420      0.675     -18.772      12.199
x223          -2.8436      8.559     -0.332      0.740     -19.774      14.086
x224          17.3657      7.896      2.199      0.030       1.747      32.984
x225          -1.2942      7.518     -0.172      0.864     -16.165      13.577
x226         -10.6091      8.287     -1.280      0.203     -27.001       5.782
x227         -10.5364      8.185     -1.287      0.200     -26.726       5.653
x228         -13.9045      8.769     -1.586      0.115     -31.250       3.441
x229          -3.3219      7.125     -0.466      0.642     -17.414      10.770
x230           9.3368      7.224      1.292      0.198      -4.952      23.626
x231          -3.4939      6.893     -0.507      0.613     -17.129      10.141
x232         -17.9265      7.575     -2.367      0.019     -32.909      -2.943
x233         -14.5557      7.828     -1.859      0.065     -30.039       0.927
x234           4.4002      6.676      0.659      0.511      -8.804      17.605
x235          -8.7390      7.761     -1.126      0.262     -24.091       6.612
x236           3.0145      8.012      0.376      0.707     -12.834      18.863
x237           3.6179      8.412      0.430      0.668     -13.021      20.257
x238           7.6114      8.020      0.949      0.344      -8.252      23.475
x239         -12.9867      7.447     -1.744      0.084     -27.717       1.744

## 6.2. Regressão Lasso - 300 dimensões

### 6.2.1. Dataset Completo

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data["enunciado_embbedings_word2vec"]]
y = enem_data["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min()*(-1))+1]*len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

1.7873995037544776

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
model_lasso = LassoCV(alphas=[0.0001, 0.001, 0.01, 0.1, 1, 10], random_state=0).fit(
    X_train, y_train
)
pred_lasso = model_lasso.predict(X_test)

print("melhor r2 score:", model_lasso.score(X_train, y_train))
print("melhor alpha:", model_lasso.alpha_)
print("RMSE com o alpha escolhido:", root_mean_squared_error(y_test, pred_lasso))

melhor r2 score: 0.14278869322754884
melhor alpha: 0.01
RMSE com o alpha escolhido: 2.26804106529649

### 6.2.2. Modelo com Corte (-3, 3)

In [ ]:
enem_filtered = enem_data.copy()
enem_filtered = enem_filtered[
    (enem_filtered["dificuldade"] >= -3) & (enem_filtered["dificuldade"] <= 3)
]
enem_filtered["dificuldade"].describe()

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_filtered["enunciado_embbedings_word2vec"]]
y = enem_filtered["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min()*(-1))+1]*len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

1.7873995037544776

In [ ]:
# Dividindo os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
model_lasso = LassoCV(alphas=[0.0001, 0.001, 0.01, 0.1, 1, 10, 100], random_state=0, tol=0.1).fit(
    X_train, y_train
)
pred_lasso = model_lasso.predict(X_test)

print("melhor r2 score:", model_lasso.score(X_train, y_train))
print("melhor alpha:", model_lasso.alpha_)
print("RMSE com o alpha escolhido:", root_mean_squared_error(y_test, pred_lasso))

melhor r2 score: 0.134062064100828
melhor alpha: 0.01
RMSE com o alpha escolhido: 2.20860448083319

## 6.3. Inclusão das provas Ledor - 300 dimensões

### 6.3.1. Regressão linear

In [ ]:
enem_data_ledor = pd.read_pickle("/content/drive/MyDrive/MED-enem/cleaned_data_ledor_vectors.pkl").dropna()
enem_data_ledor.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,year,enunciado_limpo,alternativas_limpo,vetor_enunciado,vetor_media
0,1,A atmosfera terrestre é composta pelos gases n...,A: reduzir o calor irradiado pela Terra median...,-1.70677,C,2009,absorver acontece alternativa anos aquecendo a...,A: calor industrialização irradiado mediante p...,"[[-0.072753, 0.136878, 0.160618, -0.442716, -0...","[0.016323044885853854, -0.032005971771842966, ..."
1,2,Analise a figura. Supondo que seja necessário ...,A: Concentração média de álcool no sangue ao l...,0.62043,D,2009,alternativa analise dar figura melhor necessár...,A: concentração dia longo média sangue álcool;...,"[[0.184257, -0.035359, 0.075923, 0.163333, -0....","[-0.0381658197465268, -0.027103909206661312, 0..."
2,3,Estima-se que haja atualmente no mundo 40 milh...,"A: induzir a imunidade, para proteger o organi...",2.07704,A,2009,acompanhamento aids antiviral atualmente caren...,A: contaminação imunidade induzir organismo pr...,"[[-0.117196, 0.170721, 0.426886, -0.014566, 0....","[0.0118313719691752, 0.012745790416374803, 0.0..."
3,4,"Em um experimento, preparou-se um conjunto de ...",A: os genótipos e os fenótipos idênticos.; B: ...,0.11500,B,2009,alguns amareladas apresentaram apresentava apó...,A: fenótipos genótipos idênticos; B: diferente...,"[[-0.000374, -0.127046, -0.401209, -0.020222, ...","[-0.015016743819265125, -0.01632628217041015, ..."
4,5,"Na linha de uma tradição antiga, o astrônomo g...",A: Ptolomeu apresentou as ideias mais valiosas...,0.21694,E,2009,afirmar afirmou alemão anos antiga astronômico...,A: antigas apresentou ideias ptolomeu serem tr...,"[[-0.074335, -0.090428, -0.019981, -0.153818, ...","[-0.02099789898974173, 0.008896578985698305, -..."

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data_ledor["enunciado_embbedings_word2vec"]]
y = enem_data_ledor["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

0.629376905725391

In [ ]:
# Separando em conjunto de treino e teste

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
# Adicionando constante
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

In [ ]:
# Criando o modelo e realizando predição
model = sm.OLS(y_train, X_train).fit()
pred = model.predict(X_test)

RMSE 1.0011189094119426

In [ ]:
# Cálculo do RMSE
rms = root_mean_squared_error(y_test, pred)
print('RMSE', rms)

In [ ]:
print(model.summary(alpha = 0.05))

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.699
Model:                            OLS   Adj. R-squared:                  0.097
Method:                 Least Squares   F-statistic:                     1.161
Date:                Thu, 22 May 2025   Prob (F-statistic):              0.151
Time:                        19:27:39   Log-Likelihood:                -81.498
No. Observations:                 451   AIC:                             765.0
Df Residuals:                     150   BIC:                             2003.
Df Model:                         300
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.6162      1.022      1.581      0.116      -0.404       3.636
x1             1.3108      1.766      0.742      0.459      -2.179       4.801
x2             2.3513      1.857      1.266      0.207      -1.317       6.020
x3             4.3062      2.093      2.058      0.041       0.171       8.441
x4            -1.7323      1.811     -0.956      0.340      -5.311       1.847
x5            -1.2018      1.803     -0.666      0.506      -4.765       2.361
x6            -3.4489      1.951     -1.768      0.079      -7.303       0.405
x7            -4.0266      1.780     -2.263      0.025      -7.543      -0.510
x8             2.9896      1.928      1.550      0.123      -0.820       6.800
x9            -0.6637      1.820     -0.365      0.716      -4.260       2.932
x10            1.1819      1.889      0.626      0.533      -2.551       4.915
x11            3.0383      1.733      1.754      0.082      -0.385       6.462
x12           -5.7700      1.980     -2.914      0.004      -9.683      -1.857
x13           -1.6701      1.849     -0.903      0.368      -5.323       1.983
x14            1.5317      1.832      0.836      0.405      -2.089       5.152
x15            1.0605      1.686      0.629      0.530      -2.270       4.391
x16           -0.5705      2.176     -0.262      0.794      -4.871       3.730
x17            0.8007      1.746      0.459      0.647      -2.648       4.250
x18           -3.6574      1.981     -1.846      0.067      -7.571       0.257
x19           -1.3976      1.797     -0.778      0.438      -4.948       2.153
x20           -1.1876      1.885     -0.630      0.530      -4.912       2.537
x21           -0.3254      1.826     -0.178      0.859      -3.933       3.282
x22           -0.7073      1.809     -0.391      0.696      -4.281       2.866
x23           -1.2111      1.920     -0.631      0.529      -5.006       2.584
x24            2.4211      2.009      1.205      0.230      -1.549       6.392
x25           -3.4347      1.812     -1.895      0.060      -7.016       0.146
x26            0.7288      1.916      0.380      0.704      -3.058       4.515
x27           -1.1585      1.943     -0.596      0.552      -4.999       2.682
x28            2.3584      1.915      1.232      0.220      -1.425       6.141
x29            0.2166      2.138      0.101      0.919      -4.007       4.441
x30            3.8570      1.955      1.973      0.050      -0.007       7.720
x31            3.9993      2.107      1.898      0.060      -0.163       8.162
x32           -3.8125      2.179     -1.750      0.082      -8.117       0.492
x33            2.7720      1.708      1.623      0.107      -0.602       6.146
x34            0.9196      1.878      0.490      0.625      -2.792       4.631
x35           -0.0275      1.912     -0.014      0.989      -3.805       3.750
x36            2.9816      2.019      1.477      0.142      -1.008       6.971
x37           -3.3333      1.842     -1.809      0.072      -6.973       0.307
x38           -2.7201      1.788     -1.522      0.130      -6.252       0.812
x39            1.6904      2.000      0.845      0.399      -2.262       5.643
x40           -1.8207      1.986     -0.917      0.361      -5.745       2.104
x41            1.5849      1.886      0.840      0.402      -2.142       5.312
x42            0.4063      1.869      0.217      0.828      -3.286       4.099
x43           -0.2130      1.835     -0.116      0.908      -3.839       3.413
x44            0.3183      1.720      0.185      0.853      -3.081       3.717
x45            0.9451      2.033      0.465      0.643      -3.072       4.962
x46            3.9372      1.704      2.311      0.022       0.571       7.304
x47            1.7921      2.015      0.889      0.375      -2.190       5.774
x48            0.0848      1.768      0.048      0.962      -3.408       3.577
x49           -5.2086      2.169     -2.402      0.018      -9.493      -0.924
x50            1.2494      2.145      0.583      0.561      -2.988       5.487
x51           -1.3483      1.836     -0.735      0.464      -4.975       2.279
x52            2.8095      1.919      1.464      0.145      -0.982       6.601
x53            0.5069      2.151      0.236      0.814      -3.744       4.758
x54           -1.3026      2.488     -0.524      0.601      -6.219       3.614
x55           -1.7370      1.936     -0.897      0.371      -5.562       2.088
x56            1.0824      2.017      0.537      0.592      -2.903       5.068
x57           -1.6475      1.782     -0.924      0.357      -5.169       1.874
x58           -1.6141      1.929     -0.837      0.404      -5.427       2.198
x59           -4.3185      1.909     -2.262      0.025      -8.091      -0.546
x60           -0.7424      1.982     -0.375      0.708      -4.658       3.173
x61            3.4023      1.838      1.851      0.066      -0.229       7.034
x62            0.8824      1.952      0.452      0.652      -2.975       4.740
x63           -2.0370      2.154     -0.946      0.346      -6.294       2.220
x64           -0.3235      1.916     -0.169      0.866      -4.109       3.462
x65            4.3165      2.014      2.144      0.034       0.338       8.296
x66            1.4163      1.827      0.775      0.440      -2.195       5.027
x67            3.0419      2.097      1.451      0.149      -1.101       7.185
x68           -0.4814      2.017     -0.239      0.812      -4.467       3.504
x69           -1.5550      1.988     -0.782      0.435      -5.483       2.373
x70            2.0225      1.798      1.125      0.262      -1.530       5.575
x71           -3.3396      1.952     -1.711      0.089      -7.196       0.517
x72            1.5424      1.963      0.786      0.433      -2.336       5.421
x73           -0.8176      1.739     -0.470      0.639      -4.253       2.618
x74            1.2787      1.973      0.648      0.518      -2.620       5.178
x75           -3.4964      2.012     -1.737      0.084      -7.473       0.480
x76            4.1348      1.906      2.170      0.032       0.370       7.900
x77           -2.1201      1.900     -1.116      0.266      -5.874       1.634
x78           -0.5829      1.879     -0.310      0.757      -4.296       3.131
x79            1.1899      2.022      0.589      0.557      -2.805       5.185
x80            0.3265      1.732      0.189      0.851      -3.096       3.749
x81           -1.0767      2.048     -0.526      0.600      -5.124       2.970
x82           -0.3129      2.198     -0.142      0.887      -4.657       4.031
x83            3.5013      1.980      1.769      0.079      -0.410       7.413
x84           -1.3682      1.983     -0.690      0.491      -5.287       2.550
x85            0.1353      2.359      0.057      0.954      -4.526       4.797
x86           -0.0586      1.886     -0.031      0.975      -3.786       3.669
x87           -1.2382      1.872     -0.661      0.509      -4.937       2.461
x88           -3.6890      2.216     -1.665      0.098      -8.067       0.689
x89           -2.4910      2.063     -1.208      0.229      -6.567       1.585
x90           -0.2560      1.939     -0.132      0.895      -4.088       3.576
x91           -2.0484      1.961     -1.044      0.298      -5.923       1.827
x92            3.1315      2.015      1.554      0.122      -0.850       7.113
x93           -1.4678      1.902     -0.772      0.442      -5.226       2.291
x94            2.6680      1.849      1.443      0.151      -0.985       6.321
x95           -0.9963      1.910     -0.522      0.603      -4.770       2.778
x96            0.7096      1.982      0.358      0.721      -3.206       4.625
x97           -1.0986      1.860     -0.591      0.556      -4.775       2.577
x98           -2.1484      2.078     -1.034      0.303      -6.255       1.958
x99           -4.0359      2.328     -1.734      0.085      -8.635       0.563
x100           1.5753      2.141      0.736      0.463      -2.655       5.806
x101           0.9186      2.274      0.404      0.687      -3.574       5.411
x102          -2.4530      2.228     -1.101      0.273      -6.856       1.950
x103          -5.6335      2.075     -2.716      0.007      -9.733      -1.534
x104          -2.9401      2.039     -1.442      0.151      -6.968       1.088
x105          -2.8637      1.999     -1.432      0.154      -6.814       1.087
x106          -1.5196      1.949     -0.780      0.437      -5.370       2.331
x107          -0.5250      1.971     -0.266      0.790      -4.419       3.369
x108           1.1342      1.855      0.611      0.542      -2.532       4.800
x109           3.0947      1.984      1.560      0.121      -0.826       7.015
x110          -2.0811      1.967     -1.058      0.292      -5.968       1.806
x111           0.3905      1.920      0.203      0.839      -3.403       4.184
x112          -2.6609      1.987     -1.339      0.183      -6.587       1.265
x113          -1.9053      1.842     -1.034      0.303      -5.546       1.735
x114           2.0700      2.226      0.930      0.354      -2.328       6.468
x115          -1.3137      2.200     -0.597      0.551      -5.660       3.033
x116           5.1348      2.286      2.247      0.026       0.619       9.651
x117           3.3415      2.190      1.526      0.129      -0.985       7.668
x118           1.1627      2.295      0.507      0.613      -3.372       5.697
x119           6.3617      1.962      3.243      0.001       2.485      10.238
x120           2.1062      1.891      1.114      0.267      -1.629       5.842
x121          -5.0026      2.182     -2.293      0.023      -9.313      -0.692
x122           1.1905      2.158      0.552      0.582      -3.073       5.454
x123           0.0827      1.980      0.042      0.967      -3.829       3.994
x124          -1.4454      1.862     -0.776      0.439      -5.124       2.234
x125           2.5396      1.953      1.301      0.195      -1.319       6.398
x126          -1.2343      1.898     -0.650      0.516      -4.984       2.515
x127          -2.1895      1.941     -1.128      0.261      -6.025       1.646
x128          -0.9356      1.955     -0.479      0.633      -4.799       2.927
x129          -2.4478      1.960     -1.249      0.214      -6.320       1.425
x130          -1.8382      2.239     -0.821      0.413      -6.262       2.585
x131          -1.0504      1.766     -0.595      0.553      -4.539       2.439
x132           3.7600      1.938      1.940      0.054      -0.070       7.590
x133          -0.1522      1.907     -0.080      0.937      -3.921       3.617
x134          -1.3209      2.091     -0.632      0.529      -5.453       2.812
x135          -0.1520      2.043     -0.074      0.941      -4.189       3.886
x136          -2.2351      1.879     -1.190      0.236      -5.948       1.478
x137           0.7597      1.741      0.436      0.663      -2.680       4.199
x138           0.9645      1.950      0.495      0.622      -2.889       4.818
x139           1.4205      1.851      0.767      0.444      -2.237       5.078
x140           0.3454      1.979      0.175      0.862      -3.564       4.255
x141           0.2074      1.882      0.110      0.912      -3.511       3.926
x142           0.1238      2.069      0.060      0.952      -3.965       4.212
x143          -0.7749      2.067     -0.375      0.708      -4.860       3.310
x144          -0.9391      2.133     -0.440      0.660      -5.153       3.275
x145          -2.9494      2.186     -1.349      0.179      -7.268       1.370
x146           3.3845      2.176      1.555      0.122      -0.915       7.684
x147           0.6921      1.860      0.372      0.710      -2.982       4.366
x148          -0.2425      2.311     -0.105      0.917      -4.809       4.324
x149           3.4388      1.745      1.970      0.051      -0.010       6.888
x150          -2.5591      1.865     -1.372      0.172      -6.245       1.127
x151           2.5402      2.068      1.229      0.221      -1.545       6.626
x152           1.1074      1.856      0.597      0.552      -2.560       4.775
x153          -1.9823      1.988     -0.997      0.320      -5.910       1.946
x154           1.7140      1.895      0.905      0.367      -2.030       5.458
x155           2.5219      1.997      1.263      0.209      -1.423       6.467
x156          -3.7449      1.940     -1.931      0.055      -7.578       0.088
x157           0.9285      1.824      0.509      0.612      -2.676       4.533
x158           2.6271      1.869      1.405      0.162      -1.066       6.321
x159          -0.7558      1.982     -0.381      0.703      -4.671       3.160
x160          -2.2294      2.116     -1.054      0.294      -6.410       1.951
x161          -0.4403      1.907     -0.231      0.818      -4.209       3.328
x162           1.0803      1.877      0.576      0.566      -2.629       4.789
x163          -1.1473      1.883     -0.609      0.543      -4.867       2.573
x164           0.1173      2.006      0.058      0.953      -3.847       4.082
x165          -1.2428      1.887     -0.659      0.511      -4.971       2.486
x166           1.0417      2.052      0.508      0.612      -3.013       5.096
x167          -1.4200      1.851     -0.767      0.444      -5.078       2.238
x168          -0.4004      2.120     -0.189      0.850      -4.589       3.788
x169           2.6675      1.998      1.335      0.184      -1.280       6.615
x170          -0.0835      1.774     -0.047      0.963      -3.588       3.422
x171           2.4514      1.919      1.277      0.203      -1.341       6.244
x172           1.7407      1.964      0.886      0.377      -2.141       5.622
x173           1.3554      1.991      0.681      0.497      -2.578       5.289
x174          -2.3690      1.985     -1.193      0.235      -6.291       1.553
x175          -2.8709      1.970     -1.458      0.147      -6.763       1.021
x176          -2.6935      1.866     -1.444      0.151      -6.380       0.993
x177           2.6117      1.973      1.324      0.188      -1.287       6.510
x178          -1.0085      1.841     -0.548      0.585      -4.646       2.629
x179           4.5853      1.893      2.422      0.017       0.845       8.326
x180          -2.2153      2.019     -1.097      0.274      -6.204       1.774
x181          -0.6222      1.902     -0.327      0.744      -4.381       3.137
x182           2.7949      1.954      1.430      0.155      -1.066       6.655
x183           0.5912      1.878      0.315      0.753      -3.119       4.301
x184           2.6905      1.955      1.377      0.171      -1.171       6.552
x185           1.7501      1.854      0.944      0.347      -1.913       5.413
x186          -2.1929      1.807     -1.213      0.227      -5.764       1.378
x187          -0.5479      2.043     -0.268      0.789      -4.584       3.489
x188          -0.8670      1.997     -0.434      0.665      -4.812       3.078
x189           1.7705      1.890      0.937      0.350      -1.964       5.505
x190          -0.3747      1.979     -0.189      0.850      -4.285       3.535
x191          -1.5993      1.914     -0.836      0.405      -5.381       2.182
x192           1.8388      1.767      1.041      0.300      -1.653       5.331
x193          -2.0826      1.942     -1.073      0.285      -5.919       1.754
x194          -0.6742      1.914     -0.352      0.725      -4.457       3.108
x195          -0.4376      2.012     -0.217      0.828      -4.414       3.539
x196           2.2383      2.054      1.090      0.278      -1.820       6.296
x197           0.2456      2.204      0.111      0.911      -4.110       4.601
x198          -1.7502      1.791     -0.977      0.330      -5.288       1.788
x199          -1.4739      2.112     -0.698      0.486      -5.648       2.700
x200           2.1086      1.998      1.055      0.293      -1.840       6.057
x201           0.2972      1.715      0.173      0.863      -3.092       3.686
x202           2.4899      2.139      1.164      0.246      -1.737       6.717
x203           2.3872      2.284      1.045      0.298      -2.127       6.901
x204          -0.2238      1.881     -0.119      0.905      -3.940       3.493
x205           3.5361      1.966      1.799      0.074      -0.348       7.420
x206          -0.5843      1.765     -0.331      0.741      -4.071       2.903
x207          -1.8280      2.156     -0.848      0.398      -6.087       2.431
x208          -0.2789      1.902     -0.147      0.884      -4.038       3.480
x209          -0.8151      2.077     -0.392      0.695      -4.919       3.289
x210          -4.6246      1.831     -2.526      0.013      -8.242      -1.008
x211           2.7253      2.059      1.323      0.188      -1.344       6.795
x212          -1.5731      1.705     -0.923      0.358      -4.941       1.795
x213           2.8989      2.042      1.419      0.158      -1.137       6.935
x214          -1.7614      2.094     -0.841      0.402      -5.899       2.377
x215          -0.3624      2.069     -0.175      0.861      -4.451       3.726
x216           3.3791      1.847      1.830      0.069      -0.270       7.028
x217          -0.5382      1.886     -0.285      0.776      -4.264       3.188
x218           0.7229      2.247      0.322      0.748      -3.717       5.163
x219           1.2452      1.899      0.656      0.513      -2.507       4.997
x220           3.5016      1.883      1.860      0.065      -0.219       7.222
x221           1.1680      1.996      0.585      0.559      -2.776       5.112
x222          -1.6321      1.957     -0.834      0.406      -5.498       2.234
x223          -2.5555      2.095     -1.220      0.224      -6.695       1.584
x224           0.5848      1.930      0.303      0.762      -3.229       4.399
x225           2.0402      1.868      1.092      0.277      -1.651       5.732
x226          -2.2379      1.989     -1.125      0.262      -6.169       1.693
x227          -3.9174      2.035     -1.925      0.056      -7.939       0.104
x228          -1.2874      1.963     -0.656      0.513      -5.166       2.591
x229           0.7910      1.990      0.398      0.692      -3.140       4.722
x230           3.7456      1.868      2.005      0.047       0.055       7.437
x231           0.2661      1.807      0.147      0.883      -3.305       3.837
x232          -1.6373      2.054     -0.797      0.427      -5.696       2.422
x233          -1.3953      1.944     -0.718      0.474      -5.237       2.447
x234          -4.2514      1.762     -2.413      0.017      -7.733      -0.769
x235          -0.9893      2.019     -0.490      0.625      -4.978       2.999
x236           3.5607      1.899      1.875      0.063      -0.192       7.314
x237          -0.5592      1.954     -0.286      0.775      -4.419       3.301
x238           3.4431      2.124      1.621      0.107      -0.755       7.641
x239          -1.7028      1.909     -0.892      0.374      -5.476       2.070

### 6.3.2. Lasso

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data_ledor["enunciado_embbedings_word2vec"]]
y = enem_data_ledor["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

0.629376905725391

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
model_lasso = LassoCV(alphas=[0.0001, 0.001, 0.01, 0.1, 1, 10], random_state=0).fit(
    X_train, y_train
)
pred_lasso = model_lasso.predict(X_test)
print('melhor r2 score:', model_lasso.score(X_train, y_train))
print('melhor alpha:', model_lasso.alpha_)
print('RMSE com o alpha escolhido:', root_mean_squared_error(y_test, pred_lasso))

melhor r2 score: 0.20644803088589936
melhor alpha: 0.001
RMSE com o alpha escolhido: 0.5093419924430485

##6.4. Regressão linear - 100 dimensões

In [ ]:
enem_data_100 = pd.read_pickle("/content/drive/MyDrive/MED-enem/cleaned_data_vectors_100.pkl").dropna()
enem_data_100.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,ano,enunciado_limpo,alternativas_limpo,vetor_enunciado,vetor_media
0,91,Para realizar o desentupimento de tubulações d...,A: Al; B: Co; C: Cu(OH)2; D: Fe(OH)2; E: Pb,1.13773,A,2019,adicionada aumentando aumentar básico calor co...,A: al; B: co; C: cu oh; D: fe oh; E: pb,"[[0.163096, 0.127435, -0.249899, -0.089416, 0....","[0.08290613839012939, -0.07632909273338873, 0...."
1,92,As redes de alta tensão para transmissão de en...,A: Fazer o aterramento dos arames da cerca.; B...,1.45214,A,2019,alta animais aproximarem arame campo cerca cer...,A: arames aterramento cerca fazer; B: acrescen...,"[[0.263261, 0.06409, -0.264677, 0.473302, -0.1...","[-0.01782597419925225, -0.06925118028019102, 0..."
2,93,A esquistossomose (barriga-dʼágua) caracteriza...,A: impedir a penetração do parasita pela pele....,0.58402,E,2019,anticorpos após barriga baseia baço biomphalar...,A: impedir parasita pele penetração; B: caramu...,"[[0.169307, 0.133243, 0.04853, -0.009939, -0.1...","[0.10779110447650678, -0.06825856033206117, 0...."
3,94,"Em 1962, um jingle (vinheta musical) criado po...",A: Aquecer a casa e os corpos.; B: Evitar a en...,0.41535,C,2019,abriria animado apesar aquecer associar batia ...,A: aquecer casa corpos; B: casa corpos entrada...,"[[-0.343659, -0.018934, -0.158586, 0.218599, 0...","[0.02177992160146709, 0.014867862881681718, -0..."
4,95,Glicólise é um processo que ocorre nas células...,A: libera 112 kJ por mol de glicose.; B: liber...,2.21432,A,2019,alguns anaeróbico casos combustão completament...,A: glicose kj libera mol; B: glicose kj libera...,"[[-0.304121, -0.076877, -0.194382, 0.040576, -...","[0.02815826823253457, -0.0134348290711187, 0.0..."

###6.4.1 Dataset completo

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data_100["enunciado_embbedings_word2vec"]]
y = enem_data_100["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

0.6375985567450835

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
# Adicionando constante
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

In [ ]:
# Criando o modelo e realizando predição
model = sm.OLS(y_train, X_train).fit()
pred = model.predict(X_test)

RMSE 0.584520228126551

In [ ]:
# Cálculo do RMSE
rms = root_mean_squared_error(y_test, pred)
print('RMSE', rms)

In [ ]:
print(model.summary(alpha = 0.05))

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.270
Model:                            OLS   Adj. R-squared:                  0.058
Method:                 Least Squares   F-statistic:                     1.274
Date:                Thu, 22 May 2025   Prob (F-statistic):             0.0587
Time:                        19:27:40   Log-Likelihood:                -286.06
No. Observations:                 446   AIC:                             774.1
Df Residuals:                     345   BIC:                             1188.
Df Model:                         100
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.3947      0.511      4.689      0.000       1.390       3.399
x1             1.2293      1.085      1.133      0.258      -0.904       3.363
x2            -1.2255      1.005     -1.219      0.224      -3.203       0.752
x3            -0.2313      1.009     -0.229      0.819      -2.216       1.754
x4            -0.1402      0.959     -0.146      0.884      -2.027       1.746
x5            -0.2286      0.954     -0.240      0.811      -2.105       1.647
x6             0.5441      0.954      0.570      0.569      -1.333       2.421
x7             0.2667      0.989      0.270      0.788      -1.678       2.212
x8            -0.0436      0.926     -0.047      0.962      -1.865       1.778
x9             0.6614      0.931      0.711      0.478      -1.169       2.492
x10            0.4163      1.046      0.398      0.691      -1.642       2.475
x11            0.0661      1.010      0.065      0.948      -1.920       2.052
x12            0.0835      0.950      0.088      0.930      -1.786       1.953
x13            0.3316      1.007      0.329      0.742      -1.649       2.312
x14           -0.1173      0.923     -0.127      0.899      -1.932       1.698
x15            0.1245      0.940      0.132      0.895      -1.725       1.974
x16            0.9195      0.864      1.064      0.288      -0.779       2.618
x17            0.9627      0.935      1.030      0.304      -0.876       2.802
x18           -0.1374      0.853     -0.161      0.872      -1.815       1.541
x19           -0.7034      0.989     -0.712      0.477      -2.648       1.241
x20            1.0045      0.939      1.069      0.286      -0.843       2.852
x21           -0.0966      0.886     -0.109      0.913      -1.839       1.646
x22           -0.1124      0.917     -0.123      0.903      -1.916       1.691
x23            0.0998      0.985      0.101      0.919      -1.838       2.037
x24           -0.2388      0.922     -0.259      0.796      -2.052       1.575
x25           -1.4715      0.922     -1.596      0.111      -3.285       0.342
x26           -1.4491      0.938     -1.546      0.123      -3.293       0.395
x27            1.7684      0.903      1.959      0.051      -0.007       3.544
x28           -0.4776      0.964     -0.495      0.621      -2.374       1.419
x29            0.6699      0.816      0.821      0.412      -0.936       2.276
x30            0.0029      1.037      0.003      0.998      -2.037       2.043
x31            0.7103      0.841      0.844      0.399      -0.944       2.365
x32            0.3569      0.989      0.361      0.718      -1.587       2.301
x33            0.8265      0.792      1.044      0.297      -0.731       2.384
x34            1.0094      0.791      1.276      0.203      -0.546       2.565
x35            0.8598      0.982      0.876      0.382      -1.071       2.790
x36           -0.1986      1.110     -0.179      0.858      -2.383       1.986
x37           -1.3455      1.007     -1.336      0.182      -3.326       0.635
x38            1.3280      0.991      1.340      0.181      -0.621       3.277
x39           -0.3287      0.927     -0.354      0.723      -2.152       1.495
x40            2.2949      0.941      2.440      0.015       0.445       4.145
x41           -0.0312      0.832     -0.037      0.970      -1.669       1.606
x42           -1.1641      0.915     -1.273      0.204      -2.963       0.635
x43           -0.8028      0.955     -0.841      0.401      -2.680       1.075
x44           -0.2661      0.917     -0.290      0.772      -2.070       1.538
x45           -0.1959      0.944     -0.207      0.836      -2.053       1.661
x46           -0.2045      0.967     -0.212      0.833      -2.106       1.697
x47            0.8714      1.033      0.843      0.400      -1.161       2.904
x48           -0.7471      0.934     -0.800      0.424      -2.584       1.090
x49            1.3628      1.033      1.319      0.188      -0.669       3.395
x50            0.1775      0.911      0.195      0.846      -1.615       1.969
x51           -0.3935      0.941     -0.418      0.676      -2.245       1.458
x52           -0.8379      0.844     -0.992      0.322      -2.499       0.823
x53            0.3203      0.964      0.332      0.740      -1.577       2.217
x54            0.8053      0.970      0.830      0.407      -1.103       2.714
x55            0.4537      0.956      0.475      0.635      -1.427       2.334
x56            1.0068      0.969      1.039      0.299      -0.898       2.912
x57            0.3551      0.969      0.367      0.714      -1.550       2.261
x58           -1.4339      0.899     -1.595      0.112      -3.202       0.334
x59           -0.0605      0.997     -0.061      0.952      -2.021       1.900
x60            0.0138      0.945      0.015      0.988      -1.844       1.872
x61           -0.3802      0.988     -0.385      0.701      -2.323       1.563
x62           -1.1294      0.994     -1.136      0.257      -3.085       0.827
x63           -0.3742      0.931     -0.402      0.688      -2.205       1.456
x64            0.9895      1.007      0.983      0.326      -0.991       2.970
x65           -0.4618      0.960     -0.481      0.631      -2.350       1.426
x66           -0.3401      0.919     -0.370      0.712      -2.148       1.468
x67            0.3060      0.953      0.321      0.748      -1.569       2.181
x68            0.9000      1.026      0.877      0.381      -1.118       2.918
x69            1.5549      0.931      1.670      0.096      -0.277       3.387
x70           -0.4935      0.949     -0.520      0.603      -2.359       1.372
x71            0.8057      0.986      0.817      0.414      -1.133       2.745
x72           -0.8887      0.902     -0.985      0.325      -2.663       0.885
x73           -0.4524      1.015     -0.446      0.656      -2.449       1.544
x74            0.2534      0.910      0.279      0.781      -1.536       2.043
x75            1.1875      0.907      1.310      0.191      -0.596       2.971
x76            1.1518      0.973      1.183      0.238      -0.763       3.066
x77           -0.6887      0.950     -0.725      0.469      -2.556       1.179
x78           -1.0679      1.017     -1.050      0.294      -3.068       0.933
x79           -0.2869      0.861     -0.333      0.739      -1.981       1.407
x80            0.1466      0.914      0.160      0.873      -1.650       1.944
x81           -0.7074      0.929     -0.761      0.447      -2.536       1.121
x82           -0.3343      0.910     -0.368      0.713      -2.123       1.455
x83            0.7214      0.986      0.732      0.465      -1.217       2.660
x84            0.7983      0.880      0.907      0.365      -0.932       2.529
x85           -1.4192      0.978     -1.451      0.148      -3.343       0.505
x86           -0.6557      0.887     -0.739      0.460      -2.400       1.089
x87            0.3676      0.965      0.381      0.704      -1.531       2.266
x88           -2.0305      1.107     -1.835      0.067      -4.207       0.146
x89           -2.3357      0.855     -2.733      0.007      -4.017      -0.655
x90           -0.8004      0.926     -0.864      0.388      -2.622       1.021
x91           -0.4286      0.819     -0.523      0.601      -2.040       1.182
x92            1.4410      0.923      1.560      0.120      -0.375       3.257
x93           -0.5093      0.947     -0.538      0.591      -2.372       1.353
x94           -0.3417      0.931     -0.367      0.714      -2.173       1.489
x95            0.1221      0.903      0.135      0.893      -1.655       1.899
x96           -0.3955      0.876     -0.451      0.652      -2.119       1.328
x97           -0.0290      1.003     -0.029      0.977      -2.002       1.944
x98            0.3530      0.872      0.405      0.686      -1.363       2.069
x99           -0.1066      0.948     -0.113      0.910      -1.971       1.757
x100           0.7253      0.954      0.761      0.447      -1.150       2.601
==============================================================================
Omnibus:                       92.025   Durbin-Watson:                   2.085
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              633.881
Skew:                           0.678   Prob(JB):                    2.26e-138
Kurtosis:                       8.681   Cond. No.                         104.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

###6.4.2. Modelo com Corte (-3,3)

In [ ]:
enem_filtered_100 = enem_data_100.copy()
enem_filtered_100 = enem_filtered_100[
    (enem_filtered_100["dificuldade"] >= -3) & (enem_filtered_100["dificuldade"] <= 3)
]
enem_filtered_100["dificuldade"].describe()

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_filtered_100["enunciado_embbedings_word2vec"]]
y = enem_filtered_100["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

1.7873995037544776

In [ ]:
# Dividindo os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
# Adicionando constante
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

In [ ]:
# Criando o modelo e realizando predição
model = sm.OLS(y_train, X_train).fit()
pred = model.predict(X_test)

In [ ]:
# Cálculo do RMSE
rms = root_mean_squared_error(y_test, pred)
print("RMSE:", rms)

RMSE 2.4710302449839294

In [ ]:
print(model.summary(alpha = 0.05))

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.343
Model:                            OLS   Adj. R-squared:                  0.145
Method:                 Least Squares   F-statistic:                     1.735
Date:                Thu, 22 May 2025   Prob (F-statistic):           0.000158
Time:                        19:27:41   Log-Likelihood:                -870.76
No. Observations:                 434   AIC:                             1944.
Df Residuals:                     333   BIC:                             2355.
Df Model:                         100
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.3130      2.166      3.376      0.001       3.052      11.575
x1             3.8304      4.105      0.933      0.351      -4.244      11.905
x2            -1.5063      3.816     -0.395      0.693      -9.012       5.999
x3             1.0890      3.875      0.281      0.779      -6.534       8.712
x4             3.3875      3.782      0.896      0.371      -4.052      10.827
x5            -1.3443      3.791     -0.355      0.723      -8.802       6.113
x6             1.1797      3.861      0.306      0.760      -6.416       8.775
x7             2.2199      3.854      0.576      0.565      -5.361       9.801
x8            -4.9536      3.943     -1.256      0.210     -12.710       2.802
x9             5.0800      3.759      1.351      0.177      -2.314      12.474
x10           -6.7399      4.475     -1.506      0.133     -15.542       2.062
x11            2.1563      3.971      0.543      0.587      -5.655       9.967
x12           -1.9039      3.948     -0.482      0.630      -9.671       5.863
x13            3.1265      3.930      0.796      0.427      -4.603      10.856
x14           -1.4774      3.773     -0.392      0.696      -8.899       5.944
x15           -2.7555      3.722     -0.740      0.460     -10.078       4.567
x16           -2.2968      3.472     -0.661      0.509      -9.127       4.534
x17            4.7363      3.628      1.305      0.193      -2.400      11.873
x18           -4.4830      3.277     -1.368      0.172     -10.929       1.963
x19           -2.1629      4.107     -0.527      0.599     -10.242       5.916
x20           -2.7813      3.895     -0.714      0.476     -10.443       4.881
x21           -0.4889      3.636     -0.134      0.893      -7.641       6.663
x22            0.3278      3.552      0.092      0.927      -6.658       7.314
x23           -0.9352      3.921     -0.239      0.812      -8.648       6.777
x24          -10.2691      3.706     -2.771      0.006     -17.560      -2.979
x25           -1.8883      3.530     -0.535      0.593      -8.832       5.055
x26            0.8037      3.635      0.221      0.825      -6.347       7.954
x27           -0.3368      3.550     -0.095      0.924      -7.320       6.646
x28            2.0092      4.123      0.487      0.626      -6.101      10.119
x29            1.4862      3.445      0.431      0.666      -5.291       8.263
x30            3.8081      4.235      0.899      0.369      -4.524      12.140
x31            2.6079      3.259      0.800      0.424      -3.802       9.018
x32            2.1029      3.726      0.564      0.573      -5.227       9.433
x33           -2.4357      3.301     -0.738      0.461      -8.928       4.057
x34            1.3780      3.089      0.446      0.656      -4.698       7.454
x35            4.5206      3.902      1.159      0.247      -3.154      12.196
x36            3.1691      4.549      0.697      0.487      -5.780      12.118
x37            0.1490      4.047      0.037      0.971      -7.812       8.110
x38            3.5639      3.904      0.913      0.362      -4.117      11.244
x39            0.9161      3.627      0.253      0.801      -6.219       8.052
x40            8.4858      3.759      2.257      0.025       1.091      15.881
x41           -3.3967      3.471     -0.979      0.328     -10.224       3.430
x42           -3.7525      3.505     -1.070      0.285     -10.648       3.143
x43           -5.3662      3.790     -1.416      0.158     -12.821       2.088
x44           -0.6701      3.723     -0.180      0.857      -7.993       6.653
x45           -1.8553      3.773     -0.492      0.623      -9.278       5.567
x46            0.0430      3.969      0.011      0.991      -7.765       7.851
x47           -3.0818      4.123     -0.748      0.455     -11.192       5.028
x48           -0.9386      4.047     -0.232      0.817      -8.900       7.023
x49           -1.7332      4.125     -0.420      0.675      -9.848       6.382
x50           -0.1705      3.759     -0.045      0.964      -7.565       7.224
x51           -4.4026      3.820     -1.153      0.250     -11.916       3.111
x52           -0.6305      3.354     -0.188      0.851      -7.228       5.967
x53           -0.4535      3.827     -0.118      0.906      -7.981       7.074
x54           -0.5750      3.892     -0.148      0.883      -8.231       7.081
x55            5.2557      3.661      1.436      0.152      -1.945      12.457
x56            5.0730      3.862      1.314      0.190      -2.524      12.670
x57            3.0397      4.044      0.752      0.453      -4.915      10.994
x58           -1.4545      3.571     -0.407      0.684      -8.480       5.571
x59           -6.9071      4.018     -1.719      0.087     -14.811       0.997
x60           -2.1167      3.614     -0.586      0.559      -9.226       4.993
x61           -0.8290      3.772     -0.220      0.826      -8.249       6.591
x62           -7.5711      4.076     -1.858      0.064     -15.588       0.446
x63           -0.7273      3.708     -0.196      0.845      -8.022       6.567
x64            0.2280      4.125      0.055      0.956      -7.887       8.343
x65            1.7817      3.833      0.465      0.642      -5.759       9.322
x66            1.9686      3.599      0.547      0.585      -5.111       9.048
x67            0.3600      3.793      0.095      0.924      -7.102       7.822
x68            1.3448      4.060      0.331      0.741      -6.642       9.332
x69            4.8698      3.480      1.400      0.163      -1.975      11.714
x70            1.9309      3.823      0.505      0.614      -5.590       9.451
x71          -10.1592      3.821     -2.659      0.008     -17.676      -2.642
x72            0.6220      3.453      0.180      0.857      -6.171       7.415
x73           -1.9668      3.829     -0.514      0.608      -9.499       5.566
x74            8.5554      3.618      2.365      0.019       1.439      15.672
x75            7.4198      3.607      2.057      0.040       0.325      14.515
x76            4.1369      3.864      1.071      0.285      -3.463      11.737
x77           -6.7603      3.819     -1.770      0.078     -14.273       0.752
x78            0.7322      4.000      0.183      0.855      -7.137       8.601
x79           -0.9845      3.570     -0.276      0.783      -8.006       6.037
x80           -0.3495      3.640     -0.096      0.924      -7.510       6.810
x81           -4.6274      3.794     -1.220      0.223     -12.090       2.835
x82           -2.0189      3.594     -0.562      0.575      -9.088       5.050
x83           -5.3000      3.703     -1.431      0.153     -12.583       1.983
x84           -0.1551      3.592     -0.043      0.966      -7.222       6.911
x85           -6.5736      3.991     -1.647      0.100     -14.425       1.278
x86           -7.2603      3.621     -2.005      0.046     -14.383      -0.138
x87            4.4919      3.865      1.162      0.246      -3.112      12.096
x88           -7.0052      4.258     -1.645      0.101     -15.381       1.371
x89           -5.0883      3.442     -1.478      0.140     -11.858       1.682
x90           -1.9746      3.772     -0.524      0.601      -9.394       5.445
x91           -6.9390      3.322     -2.089      0.038     -13.475      -0.403
x92            1.4198      3.604      0.394      0.694      -5.670       8.509
x93            2.8554      3.744      0.763      0.446      -4.509      10.220
x94           -2.9487      3.816     -0.773      0.440     -10.456       4.559
x95           -2.7066      3.680     -0.735      0.463      -9.946       4.533
x96            2.3662      3.465      0.683      0.495      -4.450       9.182
x97           -0.8973      3.899     -0.230      0.818      -8.568       6.773
x98            1.9426      3.494      0.556      0.579      -4.931       8.816
x99            6.9858      3.848      1.816      0.070      -0.583      14.555
x100           3.7878      3.651      1.037      0.300      -3.394      10.970
==============================================================================
Omnibus:                        0.299   Durbin-Watson:                   1.980
Prob(Omnibus):                  0.861   Jarque-Bera (JB):                0.410
Skew:                          -0.043   Prob(JB):                        0.815
Kurtosis:                       2.876   Cond. No.                         108.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## 6.5. Regressão linear - 50 dimensões

In [ ]:
enem_data_50 = pd.read_pickle("/content/drive/MyDrive/MED-enem/cleaned_data_vectors_50.pkl").dropna()
enem_data_50.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,ano,enunciado_limpo,alternativas_limpo,vetor_enunciado,vetor_media
0,91,Para realizar o desentupimento de tubulações d...,A: Al; B: Co; C: Cu(OH)2; D: Fe(OH)2; E: Pb,1.13773,A,2019,adicionada aumentando aumentar básico calor co...,A: al; B: co; C: cu oh; D: fe oh; E: pb,"[[0.167646, 0.032219, 0.126166, -0.468676, -0....","[0.15969267525428602, 0.1656768145310411, 0.05..."
1,92,As redes de alta tensão para transmissão de en...,A: Fazer o aterramento dos arames da cerca.; B...,1.45214,A,2019,alta animais aproximarem arame campo cerca cer...,A: arames aterramento cerca fazer; B: acrescen...,"[[0.254412, 0.464122, -0.360113, -0.075608, -0...","[0.07740464107169268, 0.07946692328326978, 0.0..."
2,93,A esquistossomose (barriga-dʼágua) caracteriza...,A: impedir a penetração do parasita pela pele....,0.58402,E,2019,anticorpos após barriga baseia baço biomphalar...,A: impedir parasita pele penetração; B: caramu...,"[[-0.21228, 0.511012, -0.102683, -0.056822, 0....","[0.025618789104842825, 0.08897740299621466, 0...."
3,94,"Em 1962, um jingle (vinheta musical) criado po...",A: Aquecer a casa e os corpos.; B: Evitar a en...,0.41535,C,2019,abriria animado apesar aquecer associar batia ...,A: aquecer casa corpos; B: casa corpos entrada...,"[[-0.219446, -0.167518, -0.241492, 0.002842, -...","[-0.016323587822946992, -0.038351687000078315,..."
4,95,Glicólise é um processo que ocorre nas células...,A: libera 112 kJ por mol de glicose.; B: liber...,2.21432,A,2019,alguns anaeróbico casos combustão completament...,A: glicose kj libera mol; B: glicose kj libera...,"[[0.108379, -0.268218, -0.0819, -0.138854, -0....","[0.01706921740821222, 0.138990388950333, 0.026..."

###6.5.1. Dataset completo

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data_50["enunciado_embbedings_word2vec"]]
y = enem_data_50["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

0.6375985567450835

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
# Adicionando constante
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

In [ ]:
# Criando o modelo e realizando predição
model = sm.OLS(y_train, X_train).fit()
pred = model.predict(X_test)

In [ ]:
# Cálculo do RMSE
rms = root_mean_squared_error(y_test, pred)
print('RMSE', rms)

RMSE 0.54070010642622

In [ ]:
print(model.summary(alpha = 0.05))

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.173
Model:                            OLS   Adj. R-squared:                  0.068
Method:                 Least Squares   F-statistic:                     1.648
Date:                Thu, 22 May 2025   Prob (F-statistic):            0.00524
Time:                        19:27:41   Log-Likelihood:                -313.88
No. Observations:                 446   AIC:                             729.8
Df Residuals:                     395   BIC:                             938.9
Df Model:                          50
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.9119      0.392      4.871      0.000       1.140       2.684
x1            -0.4714      0.874     -0.539      0.590      -2.191       1.248
x2            -0.2743      0.686     -0.400      0.690      -1.623       1.075
x3             0.4403      0.826      0.533      0.594      -1.184       2.065
x4            -0.7623      0.905     -0.842      0.400      -2.541       1.017
x5            -0.1287      0.772     -0.167      0.868      -1.646       1.389
x6            -1.4708      0.657     -2.239      0.026      -2.762      -0.180
x7             0.1375      0.705      0.195      0.846      -1.249       1.524
x8            -0.3368      0.642     -0.524      0.600      -1.599       0.926
x9            -1.8840      0.870     -2.166      0.031      -3.594      -0.174
x10            0.0466      0.705      0.066      0.947      -1.340       1.433
x11            0.4706      0.731      0.644      0.520      -0.966       1.907
x12           -0.6838      0.804     -0.851      0.395      -2.264       0.896
x13           -0.5680      0.652     -0.871      0.384      -1.851       0.715
x14           -0.1568      0.683     -0.229      0.819      -1.500       1.186
x15            0.2950      0.768      0.384      0.701      -1.215       1.805
x16           -0.8282      0.728     -1.138      0.256      -2.259       0.602
x17           -0.3800      0.632     -0.601      0.548      -1.622       0.862
x18            0.4708      0.812      0.580      0.562      -1.125       2.066
x19           -0.2806      0.768     -0.366      0.715      -1.790       1.229
x20            0.0245      0.602      0.041      0.968      -1.158       1.207
x21            0.2707      0.694      0.390      0.697      -1.094       1.635
x22            0.1127      0.675      0.167      0.867      -1.214       1.439
x23           -0.4244      0.674     -0.630      0.529      -1.749       0.900
x24           -0.4327      0.716     -0.604      0.546      -1.840       0.975
x25           -0.1635      0.708     -0.231      0.817      -1.556       1.228
x26           -0.7209      0.728     -0.991      0.322      -2.152       0.710
x27            0.8873      0.693      1.281      0.201      -0.475       2.249
x28           -0.4685      0.640     -0.732      0.465      -1.727       0.790
x29           -0.6672      0.750     -0.890      0.374      -2.141       0.806
x30            0.2063      0.723      0.285      0.776      -1.216       1.628
x31            0.3558      0.740      0.481      0.631      -1.099       1.810
x32            0.4507      0.749      0.601      0.548      -1.023       1.924
x33           -0.3409      0.650     -0.525      0.600      -1.618       0.936
x34           -0.1547      0.637     -0.243      0.808      -1.407       1.098
x35            0.6668      0.658      1.013      0.312      -0.627       1.961
x36            1.3804      0.680      2.029      0.043       0.043       2.718
x37           -0.5226      0.701     -0.745      0.456      -1.901       0.856
x38           -0.3545      0.795     -0.446      0.656      -1.918       1.208
x39            1.0553      0.656      1.608      0.109      -0.235       2.345
x40            0.3388      0.633      0.535      0.593      -0.907       1.584
x41            0.1623      0.613      0.265      0.791      -1.043       1.368
x42            0.7911      0.661      1.197      0.232      -0.509       2.091
x43           -1.2131      0.766     -1.583      0.114      -2.719       0.293
x44            0.0483      0.731      0.066      0.947      -1.389       1.485
x45            1.6049      0.724      2.216      0.027       0.181       3.029
x46            0.2616      0.752      0.348      0.728      -1.216       1.739
x47           -0.4110      0.718     -0.572      0.567      -1.822       1.000
x48           -0.6901      0.687     -1.005      0.315      -2.040       0.660
x49           -0.5708      0.840     -0.680      0.497      -2.221       1.080
x50            0.7173      0.631      1.136      0.257      -0.524       1.959
==============================================================================
Omnibus:                      100.177   Durbin-Watson:                   2.130
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              825.498
Skew:                           0.702   Prob(JB):                    5.56e-180
Kurtosis:                       9.515   Cond. No.                         76.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### 6.5.2. Modelo com Corte (-3,3)

In [ ]:
enem_filtered_50 = enem_data_50.copy()
enem_filtered_50 = enem_filtered_50[
    (enem_filtered_50["dificuldade"] >= -3) & (enem_filtered_50["dificuldade"] <= 3)
]
enem_filtered_50["dificuldade"].describe()

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_filtered_50["enunciado_embbedings_word2vec"]]
y = enem_filtered_50["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

In [ ]:
# Dividindo os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
# Adicionando constante
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

In [ ]:
# Criando o modelo e realizando predição
model = sm.OLS(y_train, X_train).fit()
pred = model.predict(X_test)

In [ ]:
# Cálculo do RMSE
rms = root_mean_squared_error(y_test, pred)
print("RMSE:", rms)

In [ ]:
print(model.summary(alpha = 0.05))

## 6.6. Regressão Lasso - 100 dimensões

In [ ]:
enem_data_100 = pd.read_pickle("/content/drive/MyDrive/MED-enem/cleaned_data_vectors_100.pkl").dropna()
enem_data_100.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,ano,enunciado_limpo,alternativas_limpo,vetor_enunciado,vetor_media
0,91,Para realizar o desentupimento de tubulações d...,A: Al; B: Co; C: Cu(OH)2; D: Fe(OH)2; E: Pb,1.13773,A,2019,adicionada aumentando aumentar básico calor co...,A: al; B: co; C: cu oh; D: fe oh; E: pb,"[[0.163096, 0.127435, -0.249899, -0.089416, 0....","[0.08290613839012939, -0.07632909273338873, 0...."
1,92,As redes de alta tensão para transmissão de en...,A: Fazer o aterramento dos arames da cerca.; B...,1.45214,A,2019,alta animais aproximarem arame campo cerca cer...,A: arames aterramento cerca fazer; B: acrescen...,"[[0.263261, 0.06409, -0.264677, 0.473302, -0.1...","[-0.01782597419925225, -0.06925118028019102, 0..."
2,93,A esquistossomose (barriga-dʼágua) caracteriza...,A: impedir a penetração do parasita pela pele....,0.58402,E,2019,anticorpos após barriga baseia baço biomphalar...,A: impedir parasita pele penetração; B: caramu...,"[[0.169307, 0.133243, 0.04853, -0.009939, -0.1...","[0.10779110447650678, -0.06825856033206117, 0...."
3,94,"Em 1962, um jingle (vinheta musical) criado po...",A: Aquecer a casa e os corpos.; B: Evitar a en...,0.41535,C,2019,abriria animado apesar aquecer associar batia ...,A: aquecer casa corpos; B: casa corpos entrada...,"[[-0.343659, -0.018934, -0.158586, 0.218599, 0...","[0.02177992160146709, 0.014867862881681718, -0..."
4,95,Glicólise é um processo que ocorre nas células...,A: libera 112 kJ por mol de glicose.; B: liber...,2.21432,A,2019,alguns anaeróbico casos combustão completament...,A: glicose kj libera mol; B: glicose kj libera...,"[[-0.304121, -0.076877, -0.194382, 0.040576, -...","[0.02815826823253457, -0.0134348290711187, 0.0..."

### 6.6.1. Dataset completo

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data_100["enunciado_embbedings_word2vec"]]
y = enem_data_100["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

0.6375985567450835

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
model_lasso = LassoCV(alphas=[0.0001, 0.001, 0.01, 0.1, 1, 10], random_state=0).fit(
    X_train, y_train
)
pred_lasso = model_lasso.predict(X_test)

print('melhor r2 score:', model_lasso.score(X_train, y_train))
print('melhor alpha:', model_lasso.alpha_)
print('RMSE com o alpha escolhido:', root_mean_squared_error(y_test, pred_lasso))

melhor r2 score: 0.1742266934562141
melhor alpha: 0.001
RMSE com o alpha escolhido: 0.510679154079445

###6.6.2. Modelo com Corte (-3,3)

In [ ]:
enem_filtered_100 = enem_filtered_100.copy()
enem_filtered_100 = enem_filtered_100[
    (enem_filtered_100["dificuldade"] >= -3) & (enem_filtered_100["dificuldade"] <= 3)
]
enem_filtered_100["dificuldade"].describe()

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_filtered_100["enunciado_embbedings_word2vec"]]
y = enem_filtered_100["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

1.7873995037544776

In [ ]:
# Dividindo os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
model_lasso = LassoCV(alphas=[0.0001, 0.001, 0.01, 0.1, 1, 10], random_state=0).fit(
    X_train, y_train
)
pred_lasso = model_lasso.predict(X_test)

print('melhor r2 score:', model_lasso.score(X_train, y_train))
print('melhor alpha:', model_lasso.alpha_)
print('RMSE com o alpha escolhido:', root_mean_squared_error(y_test, pred_lasso))

melhor r2 score: 0.12993724679725704
melhor alpha: 0.01
RMSE com o alpha escolhido: 2.2465387816328306

## 6.7. Regresão Lasso - 50 dimensões

In [ ]:
enem_data_50 = pd.read_pickle("/content/drive/MyDrive/MED-enem/cleaned_data_vectors_100.pkl").dropna()
enem_data_50.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,ano,enunciado_limpo,alternativas_limpo,vetor_enunciado,vetor_media
0,91,Para realizar o desentupimento de tubulações d...,A: Al; B: Co; C: Cu(OH)2; D: Fe(OH)2; E: Pb,1.13773,A,2019,adicionada aumentando aumentar básico calor co...,A: al; B: co; C: cu oh; D: fe oh; E: pb,"[[0.167646, 0.032219, 0.126166, -0.468676, -0....","[0.15969267525428602, 0.1656768145310411, 0.05..."
1,92,As redes de alta tensão para transmissão de en...,A: Fazer o aterramento dos arames da cerca.; B...,1.45214,A,2019,alta animais aproximarem arame campo cerca cer...,A: arames aterramento cerca fazer; B: acrescen...,"[[0.254412, 0.464122, -0.360113, -0.075608, -0...","[0.07740464107169268, 0.07946692328326978, 0.0..."
2,93,A esquistossomose (barriga-dʼágua) caracteriza...,A: impedir a penetração do parasita pela pele....,0.58402,E,2019,anticorpos após barriga baseia baço biomphalar...,A: impedir parasita pele penetração; B: caramu...,"[[-0.21228, 0.511012, -0.102683, -0.056822, 0....","[0.025618789104842825, 0.08897740299621466, 0...."
3,94,"Em 1962, um jingle (vinheta musical) criado po...",A: Aquecer a casa e os corpos.; B: Evitar a en...,0.41535,C,2019,abriria animado apesar aquecer associar batia ...,A: aquecer casa corpos; B: casa corpos entrada...,"[[-0.219446, -0.167518, -0.241492, 0.002842, -...","[-0.016323587822946992, -0.038351687000078315,..."
4,95,Glicólise é um processo que ocorre nas células...,A: libera 112 kJ por mol de glicose.; B: liber...,2.21432,A,2019,alguns anaeróbico casos combustão completament...,A: glicose kj libera mol; B: glicose kj libera...,"[[0.108379, -0.268218, -0.0819, -0.138854, -0....","[0.01706921740821222, 0.138990388950333, 0.026..."

### 6.7.1. Dataset completo

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data_50["enunciado_embbedings_word2vec"]]
y = enem_data_50["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

0.6375985567450835

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
model_lasso = LassoCV(alphas=[0.0001, 0.001, 0.01, 0.1, 1, 10], random_state=0).fit(
    X_train, y_train
)
pred_lasso = model_lasso.predict(X_test)

print('melhor r2 score:', model_lasso.score(X_train, y_train))
print('melhor alpha:', model_lasso.alpha_)
print('RMSE com o alpha escolhido:', root_mean_squared_error(y_test, pred_lasso))

melhor r2 score: 0.13436211723982172
melhor alpha: 0.001
RMSE com o alpha escolhido: 0.5095468517592282

###6.7.2. Modelo com Corte (-3,3)

In [ ]:
enem_filtered_50 = enem_filtered_50.copy()
enem_filtered_50 = enem_filtered_50[
    (enem_filtered_50["dificuldade"] >= -3) & (enem_filtered_50["dificuldade"] <= 3)
]
enem_filtered_50["dificuldade"].describe()

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_filtered_50["enunciado_embbedings_word2vec"]]
y = enem_filtered_50["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

1.7873995037544776

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
model_lasso = LassoCV(alphas=[0.0001, 0.001, 0.01, 0.1, 1, 10], random_state=0).fit(
    X_train, y_train
)
pred_lasso = model_lasso.predict(X_test)

print('melhor r2 score:', model_lasso.score(X_train, y_train))
print('melhor alpha:', model_lasso.alpha_)
print('RMSE com o alpha escolhido:', root_mean_squared_error(y_test, pred_lasso))

melhor r2 score: 0.134062064100828
melhor alpha: 0.01
RMSE com o alpha escolhido: 2.20860448083319

##6.8. Inclusão das provas Ledor - 100 dimensões

###6.8.1. Regressão linear

In [ ]:
enem_data_ledor_100 = pd.read_pickle("/content/drive/MyDrive/MED-enem/cleaned_data_ledor_vectors_100.pkl").dropna()
enem_data_ledor_100.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,year,enunciado_limpo,alternativas_limpo,vetor_enunciado,vetor_media
0,1,A atmosfera terrestre é composta pelos gases n...,A: reduzir o calor irradiado pela Terra median...,-1.70677,C,2009,absorver acontece alternativa anos aquecendo a...,A: calor industrialização irradiado mediante p...,"[[-0.057471, 0.039134, -0.200435, -0.474476, -...","[0.04117549896267626, -0.06806348544983741, 0...."
1,2,Analise a figura. Supondo que seja necessário ...,A: Concentração média de álcool no sangue ao l...,0.62043,D,2009,alternativa analise dar figura melhor necessár...,A: concentração dia longo média sangue álcool;...,"[[0.470062, -0.2266, 0.16833, 0.139253, 0.1976...","[0.15159045354547826, -0.08034172671085055, 0...."
2,3,Estima-se que haja atualmente no mundo 40 milh...,"A: induzir a imunidade, para proteger o organi...",2.07704,A,2009,acompanhamento aids antiviral atualmente caren...,A: contaminação imunidade induzir organismo pr...,"[[0.046831, -0.536603, 0.054299, 0.036113, 0.1...","[0.06621599993343617, 0.027898976591491507, 0...."
3,4,"Em um experimento, preparou-se um conjunto de ...",A: os genótipos e os fenótipos idênticos.; B: ...,0.11500,B,2009,alguns amareladas apresentaram apresentava apó...,A: fenótipos genótipos idênticos; B: diferente...,"[[-0.304121, -0.076877, -0.194382, 0.040576, -...","[-0.008363717363980144, -0.04735812924515743, ..."
4,5,"Na linha de uma tradição antiga, o astrônomo g...",A: Ptolomeu apresentou as ideias mais valiosas...,0.21694,E,2009,afirmar afirmou alemão anos antiga astronômico...,A: antigas apresentou ideias ptolomeu serem tr...,"[[0.234921, 0.082011, -0.108453, -0.132333, 0....","[0.03087573888225724, -0.059190621633298586, 0..."

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data_ledor_100["enunciado_embbedings_word2vec"]]
y = enem_data_ledor_100["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

0.629376905725391

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
# Adicionando constante
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

In [ ]:
# Criando modelo e realizando predição
model = sm.OLS(y_train, X_train).fit()
pred = model.predict(X_test)

In [ ]:
# Cálculo do RMSE
rms = root_mean_squared_error(y_test, pred)
print('RMSE', rms)

RMSE 0.56786166889346

In [ ]:
print(model.summary(alpha = 0.05))

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.296
Model:                            OLS   Adj. R-squared:                  0.094
Method:                 Least Squares   F-statistic:                     1.468
Date:                Fri, 23 May 2025   Prob (F-statistic):            0.00614
Time:                        21:18:08   Log-Likelihood:                -273.25
No. Observations:                 451   AIC:                             748.5
Df Residuals:                     350   BIC:                             1164.
Df Model:                         100
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.8237      0.530      3.441      0.001       0.781       2.866
x1             0.4765      1.064      0.448      0.654      -1.615       2.569
x2            -1.7060      0.946     -1.803      0.072      -3.567       0.155
x3            -1.2411      0.959     -1.295      0.196      -3.126       0.644
x4            -0.4037      0.939     -0.430      0.667      -2.250       1.443
x5            -0.7917      0.948     -0.835      0.404      -2.657       1.074
x6            -0.3166      0.934     -0.339      0.735      -2.154       1.520
x7             1.4473      0.997      1.452      0.147      -0.513       3.408
x8            -0.0822      0.940     -0.087      0.930      -1.931       1.767
x9             1.5220      0.899      1.693      0.091      -0.246       3.290
x10            0.3785      1.067      0.355      0.723      -1.719       2.476
x11           -0.3526      1.015     -0.347      0.728      -2.348       1.643
x12           -1.3467      1.010     -1.333      0.183      -3.333       0.640
x13            0.1241      1.010      0.123      0.902      -1.862       2.110
x14            0.0099      0.915      0.011      0.991      -1.790       1.809
x15           -1.0255      0.912     -1.124      0.262      -2.820       0.769
x16            1.3556      0.889      1.524      0.128      -0.394       3.105
x17            0.3726      0.856      0.435      0.664      -1.312       2.057
x18            0.1346      0.789      0.171      0.865      -1.418       1.687
x19            0.2250      0.983      0.229      0.819      -1.709       2.159
x20            0.7389      0.894      0.826      0.409      -1.020       2.498
x21           -0.0654      0.900     -0.073      0.942      -1.836       1.705
x22            0.3566      0.915      0.390      0.697      -1.442       2.155
x23           -0.3561      0.987     -0.361      0.719      -2.298       1.585
x24           -0.5079      0.923     -0.550      0.583      -2.324       1.308
x25           -0.0100      0.864     -0.012      0.991      -1.709       1.689
x26            0.2405      0.926      0.260      0.795      -1.581       2.062
x27            0.9631      0.906      1.063      0.288      -0.818       2.744
x28           -0.5177      1.023     -0.506      0.613      -2.529       1.494
x29            0.3850      0.837      0.460      0.646      -1.260       2.030
x30            0.5356      0.978      0.548      0.584      -1.387       2.458
x31            0.4243      0.828      0.513      0.609      -1.204       2.052
x32           -0.9877      0.958     -1.031      0.303      -2.871       0.896
x33            2.4719      0.843      2.933      0.004       0.814       4.130
x34           -0.5404      0.773     -0.700      0.485      -2.060       0.979
x35           -1.2999      0.936     -1.389      0.166      -3.140       0.540
x36           -0.4424      1.041     -0.425      0.671      -2.489       1.605
x37            1.2641      0.991      1.275      0.203      -0.685       3.214
x38            0.1048      0.942      0.111      0.911      -1.748       1.957
x39           -0.9246      0.893     -1.036      0.301      -2.680       0.831
x40            1.7629      0.915      1.926      0.055      -0.037       3.563
x41           -0.1997      0.821     -0.243      0.808      -1.815       1.415
x42           -0.4395      0.887     -0.495      0.621      -2.184       1.305
x43           -0.6614      0.973     -0.680      0.497      -2.575       1.252
x44            0.7781      0.880      0.884      0.377      -0.954       2.510
x45           -0.9737      0.931     -1.046      0.296      -2.805       0.858
x46            0.8693      0.915      0.950      0.343      -0.931       2.670
x47           -0.6998      0.929     -0.753      0.452      -2.527       1.127
x48           -1.4945      0.923     -1.620      0.106      -3.309       0.320
x49           -1.4012      0.944     -1.484      0.139      -3.258       0.455
x50           -1.5996      0.946     -1.691      0.092      -3.460       0.261
x51            1.1794      0.896      1.317      0.189      -0.582       2.941
x52            0.5420      0.849      0.638      0.524      -1.128       2.212
x53            2.1385      0.939      2.279      0.023       0.293       3.984
x54            0.1052      0.990      0.106      0.915      -1.843       2.053
x55           -0.1480      0.862     -0.172      0.864      -1.844       1.547
x56            0.0709      0.917      0.077      0.938      -1.733       1.875
x57           -1.2234      1.023     -1.196      0.232      -3.235       0.788
x58           -0.2023      0.918     -0.220      0.826      -2.008       1.603
x59           -1.6726      0.944     -1.771      0.077      -3.530       0.185
x60           -0.5874      0.902     -0.651      0.515      -2.361       1.187
x61           -0.1796      0.963     -0.187      0.852      -2.074       1.715
x62           -2.2654      0.968     -2.339      0.020      -4.170      -0.361
x63            0.0212      0.881      0.024      0.981      -1.711       1.753
x64            0.5525      0.929      0.595      0.552      -1.275       2.380
x65            1.1765      0.883      1.332      0.184      -0.561       2.914
x66            1.3537      0.864      1.567      0.118      -0.345       3.053
x67           -0.4219      0.927     -0.455      0.649      -2.245       1.401
x68            0.3294      0.944      0.349      0.727      -1.527       2.186
x69            2.2480      0.868      2.591      0.010       0.542       3.954
x70           -0.3175      0.855     -0.371      0.711      -1.999       1.364
x71           -1.1750      0.991     -1.185      0.237      -3.125       0.775
x72            0.4942      0.872      0.567      0.571      -1.221       2.209
x73           -0.4683      0.961     -0.487      0.626      -2.358       1.421
x74            1.3883      0.923      1.504      0.133      -0.427       3.204
x75            1.6755      0.934      1.794      0.074      -0.162       3.513
x76            0.2024      0.945      0.214      0.831      -1.657       2.062
x77           -2.0734      0.914     -2.268      0.024      -3.871      -0.276
x78           -0.2237      0.971     -0.230      0.818      -2.134       1.687
x79            0.9466      0.826      1.147      0.252      -0.677       2.570
x80            1.0496      0.950      1.105      0.270      -0.818       2.917
x81            0.1888      0.945      0.200      0.842      -1.670       2.048
x82           -1.4256      0.939     -1.517      0.130      -3.273       0.422
x83           -0.6576      0.933     -0.704      0.482      -2.494       1.178
x84           -0.3205      0.906     -0.354      0.724      -2.102       1.461
x85           -0.2270      0.960     -0.236      0.813      -2.115       1.661
x86            0.4791      0.906      0.529      0.597      -1.303       2.261
x87            1.7219      0.972      1.772      0.077      -0.189       3.633
x88            0.7294      1.022      0.713      0.476      -1.282       2.740
x89           -0.9910      0.829     -1.195      0.233      -2.621       0.639
x90           -0.5458      0.900     -0.606      0.545      -2.316       1.225
x91           -0.5517      0.801     -0.689      0.491      -2.126       1.023
x92           -0.9067      0.884     -1.025      0.306      -2.646       0.832
x93            0.2041      0.959      0.213      0.832      -1.681       2.089
x94            0.2298      0.883      0.260      0.795      -1.508       1.967
x95           -0.7123      0.892     -0.799      0.425      -2.466       1.041
x96            0.8391      0.879      0.955      0.340      -0.889       2.567
x97            0.0488      0.946      0.052      0.959      -1.813       1.910
x98            0.6895      0.881      0.782      0.435      -1.044       2.423
x99           -0.6730      0.951     -0.708      0.479      -2.542       1.196
x100           0.1955      0.919      0.213      0.832      -1.613       2.004
==============================================================================
Omnibus:                       90.701   Durbin-Watson:                   1.973
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              770.648
Skew:                           0.580   Prob(JB):                    4.53e-168
Kurtosis:                       9.298   Cond. No.                         105.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

###6.8.2. Regressão Lasso

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data_ledor_100["enunciado_embbedings_word2vec"]]
y = enem_data_ledor_100["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

0.629376905725391

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
model_lasso = LassoCV(alphas=[0.0001, 0.001, 0.01, 0.1, 1, 10], random_state=0).fit(
    X_train, y_train
)
pred_lasso = model_lasso.predict(X_test)

print('melhor r2 score:', model_lasso.score(X_train, y_train))
print('melhor alpha:', model_lasso.alpha_)
print('RMSE com o alpha escolhido:', root_mean_squared_error(y_test, pred_lasso))

melhor r2 score: 0.16727413807662184
melhor alpha: 0.001
RMSE com o alpha escolhido: 0.5050435643572783

##6.9. Inclusão das provas Ledor - 50 dimensões

###6.9.1 Regressão linear

In [ ]:
enem_data_ledor_50 = pd.read_pickle("/content/drive/MyDrive/MED-enem/cleaned_data_ledor_vectors_50.pkl").dropna()
enem_data_ledor_50.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,year,enunciado_limpo,alternativas_limpo,vetor_enunciado,vetor_media
0,1,A atmosfera terrestre é composta pelos gases n...,A: reduzir o calor irradiado pela Terra median...,-1.70677,C,2009,absorver acontece alternativa anos aquecendo a...,A: calor industrialização irradiado mediante p...,"[[0.338463, -0.080108, 0.262583, -0.003842, -0...","[0.10937313253388685, 0.1518117644762456, 0.08..."
1,2,Analise a figura. Supondo que seja necessário ...,A: Concentração média de álcool no sangue ao l...,0.62043,D,2009,alternativa analise dar figura melhor necessár...,A: concentração dia longo média sangue álcool;...,"[[0.115119, -0.029904, 0.020403, 0.350273, 0.1...","[0.001039726659655571, -0.03333791112527251, 0..."
2,3,Estima-se que haja atualmente no mundo 40 milh...,"A: induzir a imunidade, para proteger o organi...",2.07704,A,2009,acompanhamento aids antiviral atualmente caren...,A: contaminação imunidade induzir organismo pr...,"[[0.072015, -0.296274, 0.120401, 0.09635, 0.04...","[0.02792688441831012, 0.10160078826295428, 0.0..."
3,4,"Em um experimento, preparou-se um conjunto de ...",A: os genótipos e os fenótipos idênticos.; B: ...,0.11500,B,2009,alguns amareladas apresentaram apresentava apó...,A: fenótipos genótipos idênticos; B: diferente...,"[[0.108379, -0.268218, -0.0819, -0.138854, -0....","[-0.033945256138208486, 0.09432189668027255, 0..."
4,5,"Na linha de uma tradição antiga, o astrônomo g...",A: Ptolomeu apresentou as ideias mais valiosas...,0.21694,E,2009,afirmar afirmou alemão anos antiga astronômico...,A: antigas apresentou ideias ptolomeu serem tr...,"[[0.13255, 0.158937, -0.179955, -0.278152, -0....","[0.05192682555660713, 0.05507281089903436, 0.0..."

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data_ledor_50["enunciado_embbedings_word2vec"]]
y = enem_data_ledor_50["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

0.629376905725391

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
# Adicionando constante
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

In [ ]:
# Criando modelo e realizando predição
model = sm.OLS(y_train, X_train).fit()
pred = model.predict(X_test)

In [ ]:
# Cálculo do RMSE
rms = root_mean_squared_error(y_test, pred)
print('RMSE', rms)

RMSE 0.5207235087061666

In [ ]:
print(model.summary(alpha = 0.05))

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.167
Model:                            OLS   Adj. R-squared:                  0.063
Method:                 Least Squares   F-statistic:                     1.608
Date:                Fri, 23 May 2025   Prob (F-statistic):            0.00755
Time:                        21:18:12   Log-Likelihood:                -310.95
No. Observations:                 451   AIC:                             723.9
Df Residuals:                     400   BIC:                             933.6
Df Model:                          50
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.8708      0.408      4.587      0.000       1.069       2.673
x1            -0.9067      0.860     -1.054      0.293      -2.598       0.785
x2            -0.5324      0.696     -0.764      0.445      -1.901       0.837
x3            -0.0308      0.836     -0.037      0.971      -1.675       1.614
x4            -0.6166      0.946     -0.652      0.515      -2.476       1.243
x5            -0.7708      0.827     -0.932      0.352      -2.397       0.855
x6            -0.4883      0.684     -0.714      0.476      -1.833       0.857
x7             0.1578      0.717      0.220      0.826      -1.251       1.567
x8             0.0331      0.697      0.047      0.962      -1.336       1.402
x9            -0.9597      0.861     -1.115      0.266      -2.652       0.733
x10            1.5224      0.688      2.213      0.027       0.170       2.875
x11           -0.0300      0.728     -0.041      0.967      -1.460       1.400
x12            0.4203      0.824      0.510      0.610      -1.199       2.039
x13           -0.3187      0.683     -0.466      0.641      -1.662       1.025
x14           -0.1747      0.672     -0.260      0.795      -1.495       1.146
x15           -0.3108      0.749     -0.415      0.678      -1.783       1.162
x16            0.0508      0.712      0.071      0.943      -1.349       1.450
x17            0.8349      0.624      1.338      0.182      -0.392       2.062
x18           -0.0488      0.811     -0.060      0.952      -1.643       1.546
x19           -0.3501      0.822     -0.426      0.670      -1.966       1.265
x20           -0.4761      0.605     -0.787      0.432      -1.665       0.713
x21            0.0458      0.690      0.066      0.947      -1.311       1.402
x22           -1.0566      0.663     -1.594      0.112      -2.360       0.246
x23           -0.1867      0.690     -0.271      0.787      -1.543       1.170
x24            0.7028      0.689      1.019      0.309      -0.653       2.058
x25           -0.8595      0.690     -1.246      0.213      -2.216       0.497
x26           -0.3475      0.776     -0.448      0.654      -1.873       1.178
x27            0.0822      0.699      0.118      0.906      -1.291       1.456
x28            0.3883      0.709      0.548      0.584      -1.006       1.782
x29           -0.5306      0.764     -0.694      0.488      -2.033       0.972
x30           -0.3059      0.743     -0.412      0.681      -1.767       1.155
x31            0.6353      0.784      0.810      0.418      -0.907       2.177
x32            0.2003      0.752      0.266      0.790      -1.278       1.679
x33           -0.7220      0.648     -1.114      0.266      -1.997       0.553
x34           -0.1420      0.661     -0.215      0.830      -1.442       1.158
x35           -0.8389      0.661     -1.270      0.205      -2.137       0.460
x36            0.9225      0.682      1.353      0.177      -0.418       2.263
x37           -0.6530      0.757     -0.863      0.389      -2.141       0.835
x38           -0.8118      0.800     -1.015      0.311      -2.384       0.761
x39            0.1204      0.643      0.187      0.852      -1.144       1.385
x40            0.6585      0.633      1.040      0.299      -0.586       1.903
x41            1.2833      0.620      2.070      0.039       0.064       2.502
x42            0.6431      0.620      1.037      0.300      -0.576       1.862
x43           -0.6756      0.786     -0.859      0.391      -2.222       0.870
x44            0.1954      0.709      0.276      0.783      -1.198       1.589
x45            1.2586      0.720      1.748      0.081      -0.157       2.674
x46            0.9202      0.741      1.241      0.215      -0.537       2.378
x47            0.2147      0.738      0.291      0.771      -1.235       1.665
x48           -0.1978      0.636     -0.311      0.756      -1.447       1.052
x49           -0.9615      0.830     -1.158      0.248      -2.594       0.671
x50            1.4648      0.638      2.297      0.022       0.211       2.718
==============================================================================
Omnibus:                       80.902   Durbin-Watson:                   2.026
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              812.649
Skew:                           0.394   Prob(JB):                    3.43e-177
Kurtosis:                       9.529   Cond. No.                         80.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

###6.9.2. Regressão Lasso

In [ ]:
# Coletando os dados
X = [np.array(embedding) for embedding in enem_data_ledor_50["enunciado_embbedings_word2vec"]]
y = enem_data_ledor_50["dificuldade"]

In [ ]:
# Aplicando Transformações
add_list = [(y.min() * (-1)) + 1] * len(y)
y = y + add_list

# Aplicando Boxcox
y, best_lambda = stats.boxcox(y)
print(best_lambda)

0.629376905725391

In [ ]:
# Separando em conjunto de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
model_lasso = LassoCV(alphas=[0.0001, 0.001, 0.01, 0.1, 1, 10], random_state=0).fit(
    X_train, y_train
)
pred_lasso = model_lasso.predict(X_test)

print('melhor r2 score:', model_lasso.score(X_train, y_train))
print('melhor alpha:', model_lasso.alpha_)
print('RMSE com o alpha escolhido:', root_mean_squared_error(y_test, pred_lasso))

melhor r2 score: 0.12256955400055136
melhor alpha: 0.001
RMSE com o alpha escolhido: 0.5051223890309581